perl -pi -e 'BEGIN{undef $/;} s/Property:Allows_value/Property%3AAllows_value/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Available_on_platform/Property%3AAvailable_on_platform/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_URL/Property%3AHas_URL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_default_form/Property%3AHas_default_form/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_description/Property%3AHas_description/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_development_status/Property%3AHas_development_status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_download_URL/Property%3AHas_download_URL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_input_format/Property%3AHas_input_format/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_licence/Property%3AHas_licence/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_logo/Property%3AHas_logo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_output_format/Property%3AHas_output_format/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_software_maturity_status/Property%3AHas_software_maturity_status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_software_prerequisite/Property%3AHas_software_prerequisite/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_subobject/Property%3AHas_subobject/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_support_status/Property%3AHas_support_status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_title/Property%3AHas_title/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_topic/Property%3AHas_topic/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_type/Property%3AHas_type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Has_website/Property%3AHas_website/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Interaction_type/Property%3AInteraction_type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Interacts_with/Property%3AInteracts_with/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Is_open_source/Property%3AIs_open_source/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Link_type/Property%3ALink_type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Linktitle/Property%3ALinktitle/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Linktype/Property%3ALinktype/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Release_date/Property%3ARelease_date/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Subject/Property%3ASubject/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Tool_functionality_or_classification/Property%3ATool_functionality_or_classification/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Property:Written_in_language/Property%3AWritten_in_language/smg' */*/*/*
