perl -pi -e 'BEGIN{undef $/;} s/News\/DIYA:_Do_It_Yourself_Annotator/News\/DIYA%3A_Do_It_Yourself_Annotator/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/GCC2014:_June_30_-_July_2/News\/GCC2014%3A_June_30_-_July_2/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/GMOD:_Spread_the_Word!/News\/GMOD%3A_Spread_the_Word!/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/ISMB_2013:_Automated_Function_Prediction/News\/ISMB_2013%3A_Automated_Function_Prediction/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/Intern_@_Aniseed:_work_on_Chado/News\/Intern_@_Aniseed%3A_work_on_Chado/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/MAKER-P:_an_annotation_pipeline_for_plants/News\/MAKER-P%3A_an_annotation_pipeline_for_plants/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/MaizeGDB:_Choosing_GBrowse/News\/MaizeGDB%3A_Choosing_GBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/Pathway_Tools_2010:_Virtual,_Now/News\/Pathway_Tools_2010%3A_Virtual,_Now/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/Server_Maintenance:_Sept_9/News\/Server_Maintenance%3A_Sept_9/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/Tripal:_A_Web_Front_End_for_Chado/News\/Tripal%3A_A_Web_Front_End_for_Chado/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/Website_Down:_Aug_11_2008/News\/Website_Down%3A_Aug_11_2008/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/News\/YAPC::NA_2010_is_Almost_Here!/News\/YAPC%3A%3ANA_2010_is_Almost_Here!/smg' */*/*/*
