perl -pi -e 'BEGIN{undef $/;} s/Bio::GMOD/Bio%3A%3AGMOD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/BioGraphics:vista_plot_glyph/BioGraphics%3Avista_plot_glyph/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Chado::AutoDBI/Chado%3A%3AAutoDBI/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Chado::AutoDBI_Presentation/Chado%3A%3AAutoDBI_Presentation/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/DBD::mysql_on_the_Mac/DBD%3A%3Amysql_on_the_Mac/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Databases:_Primary,_Foreign_and_Alternate_Keys/Databases%3A_Primary,_Foreign_and_Alternate_Keys/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Databases:_Tables,_Rows,_and_Columns/Databases%3A_Tables,_Rows,_and_Columns/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Form:Component_information/Form%3AComponent_information/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Form:Tool_data/Form%3ATool_data/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/GMOD:About/GMOD%3AAbout/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/GO::TermFinder.1/GO%3A%3ATermFinder.1/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/GO::TermFinder\/tool_data/GO%3A%3ATermFinder\/tool_data/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Help:Editing/Help%3AEditing/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/LabDoc:_Generic_Laboratory_Protocol_Documentation_System/LabDoc%3A_Generic_Laboratory_Protocol_Documentation_System/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/MediaWiki:Common.css/MediaWiki%3ACommon.css/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ASearchByProperty\/Talk:Bio\/Schema/Special%3ASearchByProperty\/Talk%3ABio\/Schema/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Bio::Chado::Schema/Talk%3ABio%3A%3AChado%3A%3ASchema/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Bio_GMOD_GenericGenePage/Talk%3ABio_GMOD_GenericGenePage/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_Documentation_Reorganization/Talk%3AChado_Documentation_Reorganization/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_GBrowse_Summary_View/Talk%3AChado_GBrowse_Summary_View/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_Natural_Diversity_Module\/natdiv_schema_changes_call/Talk%3AChado_Natural_Diversity_Module\/natdiv_schema_changes_call/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_Natural_Diversity_Module_Working_Group/Talk%3AChado_Natural_Diversity_Module_Working_Group/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_New_Users/Talk%3AChado_New_Users/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_Post-Composed_Phenotypes/Talk%3AChado_Post-Composed_Phenotypes/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_Publication_Module/Talk%3AChado_Publication_Module/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Chado_Tables/Talk%3AChado_Tables/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Community/Talk%3ACommunity/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Community_Annotation_-_September_2010_Satellite/Talk%3ACommunity_Annotation_-_September_2010_Satellite/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Debian_Stable_Installation_Notes/Talk%3ADebian_Stable_Installation_Notes/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse/Talk%3AGBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_1_Configuration_HOWTO/Talk%3AGBrowse_1_Configuration_HOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_2.0_HOWTO/Talk%3AGBrowse_2.0_HOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Adaptors/Talk%3AGBrowse_Adaptors/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Configuration\/Balloons/Talk%3AGBrowse_Configuration\/Balloons/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Configuration\/DAS/Talk%3AGBrowse_Configuration\/DAS/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Configuration_HOWTO/Talk%3AGBrowse_Configuration_HOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Install_HOWTO/Talk%3AGBrowse_Install_HOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_MacOSX_HOWTO/Talk%3AGBrowse_MacOSX_HOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_NGS_Tutorial/Talk%3AGBrowse_NGS_Tutorial/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Persistent_Variables/Talk%3AGBrowse_Persistent_Variables/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Tutorial/Talk%3AGBrowse_Tutorial/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_Ubuntu_HOWTO/Talk%3AGBrowse_Ubuntu_HOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GBrowse_syn/Talk%3AGBrowse_syn/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GFF/Talk%3AGFF/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMODTools/Talk%3AGMODTools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMOD_Evo_Hackathon_Proposal/Talk%3AGMOD_Evo_Hackathon_Proposal/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMOD_Help_Desk/Talk%3AGMOD_Help_Desk/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMOD_Mailing_Lists/Talk%3AGMOD_Mailing_Lists/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMOD_Project_Page/Talk%3AGMOD_Project_Page/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMOD_Promotion/Talk%3AGMOD_Promotion/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:GMOD_REST_Hackathon/Talk%3AGMOD_REST_Hackathon/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Hackathon_2007_info/Talk%3AHackathon_2007_info/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Interface_test/Talk%3AInterface_test/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Introduction_to_Chado/Talk%3AIntroduction_to_Chado/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:January_2010_GMOD_Meeting/Talk%3AJanuary_2010_GMOD_Meeting/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Linux_Text_Editors/Talk%3ALinux_Text_Editors/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:LuceGene/Talk%3ALuceGene/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Overview/Talk%3AOverview/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Spring_2010_Logo_Program/Talk%3ASpring_2010_Logo_Program/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Stock_Relationship_Ontology/Talk%3AStock_Relationship_Ontology/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Talk:Textpresso/Talk%3ATextpresso/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Template_talk:GBrowse/Template_talk%3AGBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:Alexkalderimis/User_talk%3AAlexkalderimis/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:Eric_Rasche/User_talk%3AEric_Rasche/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:Girlwithglasses/User_talk%3AGirlwithglasses/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:Maccallr/User_talk%3AMaccallr/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:RSCummings/User_talk%3ARSCummings/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:Rbruggne/User_talk%3ARbruggne/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:RobertBuels/User_talk%3ARobertBuels/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/User_talk:Scott/User_talk%3AScott/smg' */*/*/*
