perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Apollo-2DChado_Integration_at_BovineBase:_Bugs_and_Suggestions/Special%3ABrowse\/Apollo-2DChado_Integration_at_BovineBase%3A_Bugs_and_Suggestions/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/BLAST-20Graphic-20Viewer-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F/Special%3ABrowse\/BLAST-20Graphic-20Viewer-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/BLAST-20Graphic-20Viewer-23http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl/Special%3ABrowse\/BLAST-20Graphic-20Viewer-23http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Bio::Chado::Schema/Special%3ABrowse\/Bio%3A%3AChado%3A%3ASchema/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Bio::GMOD/Special%3ABrowse\/Bio%3A%3AGMOD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/BioGraphics:vista_plot_glyph/Special%3ABrowse\/BioGraphics%3Avista_plot_glyph/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/BioMart-23http:-2F-2Fwww.biomart.org-2F/Special%3ABrowse\/BioMart-23http%3A-2F-2Fwww.biomart.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/BioMart-23http:-2F-2Fwww.biomart.org-2Fcommunity.html/Special%3ABrowse\/BioMart-23http%3A-2F-2Fwww.biomart.org-2Fcommunity.html/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/BioMart-23http:-2F-2Fwww.biomart.org-2Fdownload.html/Special%3ABrowse\/BioMart-23http%3A-2F-2Fwww.biomart.org-2Fdownload.html/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fbioinf.scri.sari.ac.uk-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fbioinf.scri.sari.ac.uk-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi/Special%3ABrowse\/CMap-23http%3A-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info/Special%3ABrowse\/CMap-23http%3A-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info/Special%3ABrowse\/CMap-23http%3A-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fmap.lab.nig.ac.jp:8080-2Fcmap-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fmap.lab.nig.ac.jp%3A8080-2Fcmap-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fmedvet.angis.org.au-2Fcmap-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fmedvet.angis.org.au-2Fcmap-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer/Special%3ABrowse\/CMap-23http%3A-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Frye.pw.usda.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info-3Fmap_set_aid=Barley_consensus_2003/Special%3ABrowse\/CMap-23http%3A-2F-2Frye.pw.usda.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info-3Fmap_set_aid=Barley_consensus_2003/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fsoybeanbreederstoolbox.org-2Findex.php/Special%3ABrowse\/CMap-23http%3A-2F-2Fsoybeanbreederstoolbox.org-2Findex.php/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Ftropgenedb.cirad.fr/Special%3ABrowse\/CMap-23http%3A-2F-2Ftropgenedb.cirad.fr/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.bioinfo.wsu.edu-2Fcgi-2Dbin-2Fgdr-2Fcmap-2Fmap_set_info-3Fmap_set_aid=17/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.bioinfo.wsu.edu-2Fcgi-2Dbin-2Fgdr-2Fcmap-2Fmap_set_info-3Fmap_set_aid=17/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.comparative-2Dlegumes.org-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.comparative-2Dlegumes.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.cottondb.org-2Fcmap-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.cottondb.org-2Fcmap-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.cottonmarker.org-2F/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.cottonmarker.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.gramene.org-2Fcmap/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.gramene.org-2Fcmap/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.gramene.org-2Fdb-2Fcmap/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.gramene.org-2Fdb-2Fcmap/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23http:-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM;ref_map_aids=109/Special%3ABrowse\/CMap-23http%3A-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM;ref_map_aids=109/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/CMap-23https:-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap/Special%3ABrowse\/CMap-23https%3A-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Canto-23http:-2F-2Fcuration.pombase.org-2F/Special%3ABrowse\/Canto-23http%3A-2F-2Fcuration.pombase.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Canto-23http:-2F-2Fcuration.pombase.org-2Fdemo/Special%3ABrowse\/Canto-23http%3A-2F-2Fcuration.pombase.org-2Fdemo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Canto-23http:-2F-2Fcuration.pombase.org-2Fpombe/Special%3ABrowse\/Canto-23http%3A-2F-2Fcuration.pombase.org-2Fpombe/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Canto-23http:-2F-2Fcuration.pombase.org-2Funiprot/Special%3ABrowse\/Canto-23http%3A-2F-2Fcuration.pombase.org-2Funiprot/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Canto-23https:-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin/Special%3ABrowse\/Canto-23https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Canto-23https:-2F-2Fgithub.com-2Fpombase-2Fcanto/Special%3ABrowse\/Canto-23https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:!FixAfterUpgrade/Special%3ABrowse\/Category%3A!FixAfterUpgrade/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:!Lacking_ERD/Special%3ABrowse\/Category%3A!Lacking_ERD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:2011_Spring_Training/Special%3ABrowse\/Category%3A2011_Spring_Training/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:2012_Summer_School/Special%3ABrowse\/Category%3A2012_Summer_School/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:2013_Summer_School/Special%3ABrowse\/Category%3A2013_Summer_School/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:AJAX/Special%3ABrowse\/Category%3AAJAX/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Analysis/Special%3ABrowse\/Category%3AAnalysis/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Annotation/Special%3ABrowse\/Category%3AAnnotation/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:ApiDB/Special%3ABrowse\/Category%3AApiDB/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Apollo/Special%3ABrowse\/Category%3AApollo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:BLAST/Special%3ABrowse\/Category%3ABLAST/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:BioDIG/Special%3ABrowse\/Category%3ABioDIG/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:BioMart/Special%3ABrowse\/Category%3ABioMart/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:BioPerl/Special%3ABrowse\/Category%3ABioPerl/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Biology/Special%3ABrowse\/Category%3ABiology/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:CMap/Special%3ABrowse\/Category%3ACMap/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Canto/Special%3ABrowse\/Category%3ACanto/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Categories/Special%3ABrowse\/Category%3ACategories/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Chado/Special%3ABrowse\/Category%3AChado/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Chado_FlyBase/Special%3ABrowse\/Category%3AChado_FlyBase/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Chado_Modules/Special%3ABrowse\/Category%3AChado_Modules/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Chado_Presentations/Special%3ABrowse\/Category%3AChado_Presentations/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Cloud/Special%3ABrowse\/Category%3ACloud/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Community_Annotation/Special%3ABrowse\/Category%3ACommunity_Annotation/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Comparative_Genomics/Special%3ABrowse\/Category%3AComparative_Genomics/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Computing/Special%3ABrowse\/Category%3AComputing/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Conferences/Special%3ABrowse\/Category%3AConferences/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Configuration/Special%3ABrowse\/Category%3AConfiguration/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:DAS/Special%3ABrowse\/Category%3ADAS/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Database/Special%3ABrowse\/Category%3ADatabase/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Database_Tools/Special%3ABrowse\/Category%3ADatabase_Tools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Deprecated/Special%3ABrowse\/Category%3ADeprecated/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:DictyBase/Special%3ABrowse\/Category%3ADictyBase/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Documentation/Special%3ABrowse\/Category%3ADocumentation/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Drupal/Special%3ABrowse\/Category%3ADrupal/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:ERD/Special%3ABrowse\/Category%3AERD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Education_and_Outreach/Special%3ABrowse\/Category%3AEducation_and_Outreach/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Ergatis/Special%3ABrowse\/Category%3AErgatis/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Events/Special%3ABrowse\/Category%3AEvents/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Evolution/Special%3ABrowse\/Category%3AEvolution/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Expression/Special%3ABrowse\/Category%3AExpression/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:External/Special%3ABrowse\/Category%3AExternal/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:FAQ/Special%3ABrowse\/Category%3AFAQ/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:File_Formats/Special%3ABrowse\/Category%3AFile_Formats/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:FlyBase/Special%3ABrowse\/Category%3AFlyBase/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GBrowse/Special%3ABrowse\/Category%3AGBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GBrowse_2/Special%3ABrowse\/Category%3AGBrowse_2/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GBrowse_Developer/Special%3ABrowse\/Category%3AGBrowse_Developer/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GBrowse_Plugins/Special%3ABrowse\/Category%3AGBrowse_Plugins/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GBrowse_syn/Special%3ABrowse\/Category%3AGBrowse_syn/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GFF/Special%3ABrowse\/Category%3AGFF/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GFF3/Special%3ABrowse\/Category%3AGFF3/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD-20Component/Special%3ABrowse\/Category%3AGMOD-20Component/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD-20Tools/Special%3ABrowse\/Category%3AGMOD-20Tools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMODWeb/Special%3ABrowse\/Category%3AGMODWeb/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Best_Practices/Special%3ABrowse\/Category%3AGMOD_Best_Practices/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Community/Special%3ABrowse\/Category%3AGMOD_Community/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Component/Special%3ABrowse\/Category%3AGMOD_Component/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Components/Special%3ABrowse\/Category%3AGMOD_Components/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Developers/Special%3ABrowse\/Category%3AGMOD_Developers/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Evo_Hackathon/Special%3ABrowse\/Category%3AGMOD_Evo_Hackathon/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Online_Training/Special%3ABrowse\/Category%3AGMOD_Online_Training/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Project/Special%3ABrowse\/Category%3AGMOD_Project/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Project_Logos/Special%3ABrowse\/Category%3AGMOD_Project_Logos/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Project_Presentations/Special%3ABrowse\/Category%3AGMOD_Project_Presentations/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Schools/Special%3ABrowse\/Category%3AGMOD_Schools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Tools/Special%3ABrowse\/Category%3AGMOD_Tools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_Web_Site/Special%3ABrowse\/Category%3AGMOD_Web_Site/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_in_the_Cloud/Special%3ABrowse\/Category%3AGMOD_in_the_Cloud/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GMOD_virtual_server/Special%3ABrowse\/Category%3AGMOD_virtual_server/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:GSoC/Special%3ABrowse\/Category%3AGSoC/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Galaxy/Special%3ABrowse\/Category%3AGalaxy/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Generic_Gene_Pages/Special%3ABrowse\/Category%3AGeneric_Gene_Pages/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Gramene/Special%3ABrowse\/Category%3AGramene/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:HOWTO/Special%3ABrowse\/Category%3AHOWTO/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Help/Special%3ABrowse\/Category%3AHelp/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:IGS/Special%3ABrowse\/Category%3AIGS/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Install/Special%3ABrowse\/Category%3AInstall/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:InterMine/Special%3ABrowse\/Category%3AInterMine/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:JBrowse/Special%3ABrowse\/Category%3AJBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Java/Special%3ABrowse\/Category%3AJava/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Javascript/Special%3ABrowse\/Category%3AJavascript/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Jobs/Special%3ABrowse\/Category%3AJobs/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Linux/Special%3ABrowse\/Category%3ALinux/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Logos_and_Icons/Special%3ABrowse\/Category%3ALogos_and_Icons/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:LuceGene/Special%3ABrowse\/Category%3ALuceGene/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:MAKER/Special%3ABrowse\/Category%3AMAKER/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:MGI/Special%3ABrowse\/Category%3AMGI/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:MOD_UI_Presentations/Special%3ABrowse\/Category%3AMOD_UI_Presentations/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:MOD_User_Interfaces/Special%3ABrowse\/Category%3AMOD_User_Interfaces/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Mac_OS_X/Special%3ABrowse\/Category%3AMac_OS_X/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Meetings/Special%3ABrowse\/Category%3AMeetings/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Member_Logos/Special%3ABrowse\/Category%3AMember_Logos/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Microarrays/Special%3ABrowse\/Category%3AMicroarrays/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Middleware/Special%3ABrowse\/Category%3AMiddleware/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Middleware_Presentations/Special%3ABrowse\/Category%3AMiddleware_Presentations/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Modware/Special%3ABrowse\/Category%3AModware/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:MySQL/Special%3ABrowse\/Category%3AMySQL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:NGS/Special%3ABrowse\/Category%3ANGS/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Natural_Diversity/Special%3ABrowse\/Category%3ANatural_Diversity/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Needs_Editing/Special%3ABrowse\/Category%3ANeeds_Editing/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Needs_Testing/Special%3ABrowse\/Category%3ANeeds_Testing/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:News_Items/Special%3ABrowse\/Category%3ANews_Items/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Ontologies/Special%3ABrowse\/Category%3AOntologies/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Pages_containing_blacklisted_links/Special%3ABrowse\/Category%3APages_containing_blacklisted_links/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Pages_with_broken_file_links/Special%3ABrowse\/Category%3APages_with_broken_file_links/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Pages_with_problems_or_questions/Special%3ABrowse\/Category%3APages_with_problems_or_questions/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Paper_Cuts/Special%3ABrowse\/Category%3APaper_Cuts/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:ParameciumDB/Special%3ABrowse\/Category%3AParameciumDB/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Pathway_Tools/Special%3ABrowse\/Category%3APathway_Tools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Performance/Special%3ABrowse\/Category%3APerformance/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Perl/Special%3ABrowse\/Category%3APerl/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Phenotypes/Special%3ABrowse\/Category%3APhenotypes/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Posters/Special%3ABrowse\/Category%3APosters/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:PostgreSQL/Special%3ABrowse\/Category%3APostgreSQL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Presentations/Special%3ABrowse\/Category%3APresentations/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Proposals/Special%3ABrowse\/Category%3AProposals/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:PubSearch/Special%3ABrowse\/Category%3APubSearch/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Publications/Special%3ABrowse\/Category%3APublications/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:REST/Special%3ABrowse\/Category%3AREST/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:RGD/Special%3ABrowse\/Category%3ARGD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:RPC/Special%3ABrowse\/Category%3ARPC/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Rails/Special%3ABrowse\/Category%3ARails/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Reactome/Special%3ABrowse\/Category%3AReactome/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:SAMtools/Special%3ABrowse\/Category%3ASAMtools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:SGD/Special%3ABrowse\/Category%3ASGD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:SGN/Special%3ABrowse\/Category%3ASGN/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:SOBA/Special%3ABrowse\/Category%3ASOBA/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Screenshots/Special%3ABrowse\/Category%3AScreenshots/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:SemanticLink/Special%3ABrowse\/Category%3ASemanticLink/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Semantic_web/Special%3ABrowse\/Category%3ASemantic_web/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Session/Special%3ABrowse\/Category%3ASession/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Social_Media/Special%3ABrowse\/Category%3ASocial_Media/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Software_Engineer/Special%3ABrowse\/Category%3ASoftware_Engineer/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Sybil/Special%3ABrowse\/Category%3ASybil/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:TAIR/Special%3ABrowse\/Category%3ATAIR/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:TableEdit/Special%3ABrowse\/Category%3ATableEdit/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Template/Special%3ABrowse\/Category%3ATemplate/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Textpresso/Special%3ABrowse\/Category%3ATextpresso/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Tool_data/Special%3ABrowse\/Category%3ATool_data/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Tools_using_GMOD/Special%3ABrowse\/Category%3ATools_using_GMOD/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Tripal/Special%3ABrowse\/Category%3ATripal/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Turnkey/Special%3ABrowse\/Category%3ATurnkey/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Tutorial/Special%3ABrowse\/Category%3ATutorial/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Tutorials/Special%3ABrowse\/Category%3ATutorials/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Under_Construction/Special%3ABrowse\/Category%3AUnder_Construction/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Unsupported/Special%3ABrowse\/Category%3AUnsupported/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:User_Experiences/Special%3ABrowse\/Category%3AUser_Experiences/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Users/Special%3ABrowse\/Category%3AUsers/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Visualization/Special%3ABrowse\/Category%3AVisualization/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:WFleaBase/Special%3ABrowse\/Category%3AWFleaBase/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:WebGBrowse/Special%3ABrowse\/Category%3AWebGBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Web_services/Special%3ABrowse\/Category%3AWeb_services/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Webapollo-2Dminutes/Special%3ABrowse\/Category%3AWebapollo-2Dminutes/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Webapollo/Special%3ABrowse\/Category%3AWebapollo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Wiki_Tools/Special%3ABrowse\/Category%3AWiki_Tools/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:Windows/Special%3ABrowse\/Category%3AWindows/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:WormBase/Special%3ABrowse\/Category%3AWormBase/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:XML/Special%3ABrowse\/Category%3AXML/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Category:XORT/Special%3ABrowse\/Category%3AXORT/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Chado-23https:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fgmod-2F/Special%3ABrowse\/Chado-23https%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fgmod-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Chado::AutoDBI/Special%3ABrowse\/Chado%3A%3AAutoDBI/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Chado::AutoDBI_Presentation/Special%3ABrowse\/Chado%3A%3AAutoDBI_Presentation/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/DBD::mysql_on_the_Mac/Special%3ABrowse\/DBD%3A%3Amysql_on_the_Mac/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/DIYA-23https:-2F-2Fgithub.com-2Fbioteam-2FDIYA/Special%3ABrowse\/DIYA-23https%3A-2F-2Fgithub.com-2Fbioteam-2FDIYA/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Databases:_Primary,_Foreign_and_Alternate_Keys/Special%3ABrowse\/Databases%3A_Primary,_Foreign_and_Alternate_Keys/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Databases:_Tables,_Rows,_and_Columns/Special%3ABrowse\/Databases%3A_Tables,_Rows,_and_Columns/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Face_Caucus_ApiDB:_User_Studies_and_Impact_on_Development/Special%3ABrowse\/Face_Caucus_ApiDB%3A_User_Studies_and_Impact_on_Development/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Face_Caucus_SGN:_Associating_Solanaceae_loci_with_phenotype/Special%3ABrowse\/Face_Caucus_SGN%3A_Associating_Solanaceae_loci_with_phenotype/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Face_Caucus_UCSC:_User_Interface_Issues/Special%3ABrowse\/Face_Caucus_UCSC%3A_User_Interface_Issues/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-20syn-23http:-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele;name=X:1050001..1150000/Special%3ABrowse\/GBrowse-20syn-23http%3A-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele;name=X%3A1050001..1150000/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-20syn-23http:-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri;name=chrX:620000..670000/Special%3ABrowse\/GBrowse-20syn-23http%3A-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri;name=chrX%3A620000..670000/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-20syn-23http:-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F/Special%3ABrowse\/GBrowse-20syn-23http%3A-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-20syn-23http:-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501/Special%3ABrowse\/GBrowse-20syn-23http%3A-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-20syn-23https:-2F-2Fgithub.com-2FGMOD-2FGBrowse/Special%3ABrowse\/GBrowse-20syn-23https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-23http:-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel/Special%3ABrowse\/GBrowse-23http%3A-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-23http:-2F-2Fgbrowse.org/Special%3ABrowse\/GBrowse-23http%3A-2F-2Fgbrowse.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-23http:-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse/Special%3ABrowse\/GBrowse-23http%3A-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F/Special%3ABrowse\/GBrowse-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-23http:-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F/Special%3ABrowse\/GBrowse-23http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GBrowse-23https:-2F-2Fgithub.com-2FGMOD-2FGBrowse/Special%3ABrowse\/GBrowse-23https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GMOD:About/Special%3ABrowse\/GMOD%3AAbout/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GO-20Graphic-20Viewer-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F/Special%3ABrowse\/GO-20Graphic-20Viewer-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GO-20Graphic-20Viewer-23http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl/Special%3ABrowse\/GO-20Graphic-20Viewer-23http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GO::TermFinder-23http:-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder/Special%3ABrowse\/GO%3A%3ATermFinder-23http%3A-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GO::TermFinder-23http:-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F/Special%3ABrowse\/GO%3A%3ATermFinder-23http%3A-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GO::TermFinder-2Ftool_data/Special%3ABrowse\/GO%3A%3ATermFinder-2Ftool_data/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/GO::TermFinder/Special%3ABrowse\/GO%3A%3ATermFinder/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23http:-2F-2Fgetgalaxy.org-2F/Special%3ABrowse\/Galaxy-23http%3A-2F-2Fgetgalaxy.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23http:-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers/Special%3ABrowse\/Galaxy-23http%3A-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Fdocs.galaxyproject.org/Special%3ABrowse\/Galaxy-23https%3A-2F-2Fdocs.galaxyproject.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Fgalaxyproject.github.io/Special%3ABrowse\/Galaxy-23https%3A-2F-2Fgalaxyproject.github.io/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Fgalaxyproject.org-2F/Special%3ABrowse\/Galaxy-23https%3A-2F-2Fgalaxyproject.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Fgalaxyproject.org-2Fuse-2F/Special%3ABrowse\/Galaxy-23https%3A-2F-2Fgalaxyproject.org-2Fuse-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F/Special%3ABrowse\/Galaxy-23https%3A-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Ftwitter.com-2Fgalaxyproject/Special%3ABrowse\/Galaxy-23https%3A-2F-2Ftwitter.com-2Fgalaxyproject/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Galaxy-23https:-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy/Special%3ABrowse\/Galaxy-23https%3A-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Help:Editing/Special%3ABrowse\/Help%3AEditing/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fratmine.mcw.edu-2F/Special%3ABrowse\/InterMine-23http%3A-2F-2Fratmine.mcw.edu-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fwww.flymine.org/Special%3ABrowse\/InterMine-23http%3A-2F-2Fwww.flymine.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fwww.intermine.org/Special%3ABrowse\/InterMine-23http%3A-2F-2Fwww.intermine.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fwww.mousemine.org-2F/Special%3ABrowse\/InterMine-23http%3A-2F-2Fwww.mousemine.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine/Special%3ABrowse\/InterMine-23http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fyeastmine.yeastgenome.org-2F/Special%3ABrowse\/InterMine-23http%3A-2F-2Fyeastmine.yeastgenome.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23http:-2F-2Fzmine.zfin.org-2F/Special%3ABrowse\/InterMine-23http%3A-2F-2Fzmine.zfin.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/InterMine-23https:-2F-2Fgithub.com-2Fintermine-2Fintermine.git/Special%3ABrowse\/InterMine-23https%3A-2F-2Fgithub.com-2Fintermine-2Fintermine.git/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fbeetlebase.org/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fbeetlebase.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fgenomesunzipped.org-2Fjbrowse/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fgenomesunzipped.org-2Fjbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fgithub.com-2FGMOD-2Fjbrowse/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Ficemangenome.net-2F/Special%3ABrowse\/JBrowse-23http%3A-2F-2Ficemangenome.net-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fjbrowse.org-2Fdemos/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fjbrowse.org-2Fdemos/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fjbrowse.org-2Finstall-2F/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fjbrowse.org-2Finstall-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fjbrowse.org/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fjbrowse.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Ftwitter.com-2Fusejbrowse/Special%3ABrowse\/JBrowse-23http%3A-2F-2Ftwitter.com-2Fusejbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse-23http:-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F/Special%3ABrowse\/JBrowse-23http%3A-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse2-23http:-2F-2Fjbrowse.org-2Fdemos/Special%3ABrowse\/JBrowse2-23http%3A-2F-2Fjbrowse.org-2Fdemos/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse2-23http:-2F-2Fjbrowse.org/Special%3ABrowse\/JBrowse2-23http%3A-2F-2Fjbrowse.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse2-23http:-2F-2Ftwitter.com-2Fusejbrowse/Special%3ABrowse\/JBrowse2-23http%3A-2F-2Ftwitter.com-2Fusejbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse2-23https:-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F/Special%3ABrowse\/JBrowse2-23https%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/JBrowse2-23https:-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web/Special%3ABrowse\/JBrowse2-23https%3A-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/LabDoc:_Generic_Laboratory_Protocol_Documentation_System/Special%3ABrowse\/LabDoc%3A_Generic_Laboratory_Protocol_Documentation_System/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MAKER-23http:-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi/Special%3ABrowse\/MAKER-23http%3A-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MAKER-23http:-2F-2Fhymenopteragenome.org-2Fant_genomes-2F/Special%3ABrowse\/MAKER-23http%3A-2F-2Fhymenopteragenome.org-2Fant_genomes-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MAKER-23http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html/Special%3ABrowse\/MAKER-23http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MAKER-23http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html/Special%3ABrowse\/MAKER-23http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MAKER-23http:-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi/Special%3ABrowse\/MAKER-23http%3A-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MAKER-23https:-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48/Special%3ABrowse\/MAKER-23https%3A-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MOD_User_Interfaces:_Sample_of_several_MOD_Top_Level_functions/Special%3ABrowse\/MOD_User_Interfaces%3A_Sample_of_several_MOD_Top_Level_functions/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/MOD_User_Interfaces:_outline_of_topics/Special%3ABrowse\/MOD_User_Interfaces%3A_outline_of_topics/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2F2013_Meeting:_Keynote_Announcement/Special%3ABrowse\/News-2F2013_Meeting%3A_Keynote_Announcement/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2F2013_Meeting:_Last_Day_For_Early_Birds/Special%3ABrowse\/News-2F2013_Meeting%3A_Last_Day_For_Early_Birds/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FBeta_Test_CMap:_Win_a_T-2DShirt!/Special%3ABrowse\/News-2FBeta_Test_CMap%3A_Win_a_T-2DShirt!/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FBio::Chado::Schema_0.03_Released/Special%3ABrowse\/News-2FBio%3A%3AChado%3A%3ASchema_0.03_Released/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FBio::Chado::Schema_0.05_Released/Special%3ABrowse\/News-2FBio%3A%3AChado%3A%3ASchema_0.05_Released/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FCVS_to_SVN_Conversion:_Done/Special%3ABrowse\/News-2FCVS_to_SVN_Conversion%3A_Done/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FCVS_to_SVN_Conversion:_Sept_15/Special%3ABrowse\/News-2FCVS_to_SVN_Conversion%3A_Sept_15/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FChado_in_RDF:_OpenFlyData/Special%3ABrowse\/News-2FChado_in_RDF%3A_OpenFlyData/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FDIYA:_Do_It_Yourself_Annotator/Special%3ABrowse\/News-2FDIYA%3A_Do_It_Yourself_Annotator/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FFeedback_Wanted:_JBrowse_UI_Redesign/Special%3ABrowse\/News-2FFeedback_Wanted%3A_JBrowse_UI_Redesign/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGCC2013:_Register!_Present!/Special%3ABrowse\/News-2FGCC2013%3A_Register!_Present!/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGCC2014:_June_30_-2D_July_2/Special%3ABrowse\/News-2FGCC2014%3A_June_30_-2D_July_2/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD:_Spread_the_Word!/Special%3ABrowse\/News-2FGMOD%3A_Spread_the_Word!/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD_2014_San_Diego:_Save_the_Date/Special%3ABrowse\/News-2FGMOD_2014_San_Diego%3A_Save_the_Date/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD_Americas:_March_2011/Special%3ABrowse\/News-2FGMOD_Americas%3A_March_2011/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD_Meeting:_Sept._13-2D14/Special%3ABrowse\/News-2FGMOD_Meeting%3A_Sept._13-2D14/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD_Nomination:_ISGA/Special%3ABrowse\/News-2FGMOD_Nomination%3A_ISGA/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD_Spring_Training:_Apply_Now/Special%3ABrowse\/News-2FGMOD_Spring_Training%3A_Apply_Now/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGMOD_Summer_School_2012:_Apply_Now/Special%3ABrowse\/News-2FGMOD_Summer_School_2012%3A_Apply_Now/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FGalaxy_Events:_April_2011/Special%3ABrowse\/News-2FGalaxy_Events%3A_April_2011/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FISMB_2013:_Automated_Function_Prediction/Special%3ABrowse\/News-2FISMB_2013%3A_Automated_Function_Prediction/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FIntern_@_Aniseed:_work_on_Chado/Special%3ABrowse\/News-2FIntern_@_Aniseed%3A_work_on_Chado/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FMAKER-2DP:_an_annotation_pipeline_for_plants/Special%3ABrowse\/News-2FMAKER-2DP%3A_an_annotation_pipeline_for_plants/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FMaizeGDB:_Choosing_GBrowse/Special%3ABrowse\/News-2FMaizeGDB%3A_Choosing_GBrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FPathway_Tools_2010:_Virtual,_Now/Special%3ABrowse\/News-2FPathway_Tools_2010%3A_Virtual,_Now/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FServer_Maintenance:_Sept_9/Special%3ABrowse\/News-2FServer_Maintenance%3A_Sept_9/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FTripal:_A_Web_Front_End_for_Chado/Special%3ABrowse\/News-2FTripal%3A_A_Web_Front_End_for_Chado/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FWebsite_Down:_Aug_11_2008/Special%3ABrowse\/News-2FWebsite_Down%3A_Aug_11_2008/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/News-2FYAPC::NA_2010_is_Almost_Here!/Special%3ABrowse\/News-2FYAPC%3A%3ANA_2010_is_Almost_Here!/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2F/Special%3ABrowse\/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2FECOLI-2F/Special%3ABrowse\/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2FECOLI-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2Fdownload.shtml/Special%3ABrowse\/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2Fdownload.shtml/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2Fotherpgdbs.shtml/Special%3ABrowse\/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2Fotherpgdbs.shtml/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Pathway-20Tools-23http:-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F/Special%3ABrowse\/Pathway-20Tools-23http%3A-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Allows_value/Special%3ABrowse\/Property%3AAllows_value/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Available-20on-20platform/Special%3ABrowse\/Property%3AAvailable-20on-20platform/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Available_on_platform/Special%3ABrowse\/Property%3AAvailable_on_platform/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20URL/Special%3ABrowse\/Property%3AHas-20URL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20description/Special%3ABrowse\/Property%3AHas-20description/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20development-20status/Special%3ABrowse\/Property%3AHas-20development-20status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20download-20URL/Special%3ABrowse\/Property%3AHas-20download-20URL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20input-20format/Special%3ABrowse\/Property%3AHas-20input-20format/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20licence/Special%3ABrowse\/Property%3AHas-20licence/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20logo/Special%3ABrowse\/Property%3AHas-20logo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20output-20format/Special%3ABrowse\/Property%3AHas-20output-20format/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20software-20maturity-20status/Special%3ABrowse\/Property%3AHas-20software-20maturity-20status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20software-20prerequisite/Special%3ABrowse\/Property%3AHas-20software-20prerequisite/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20support-20status/Special%3ABrowse\/Property%3AHas-20support-20status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20title/Special%3ABrowse\/Property%3AHas-20title/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20topic/Special%3ABrowse\/Property%3AHas-20topic/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has-20website/Special%3ABrowse\/Property%3AHas-20website/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_URL/Special%3ABrowse\/Property%3AHas_URL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_default_form/Special%3ABrowse\/Property%3AHas_default_form/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_description/Special%3ABrowse\/Property%3AHas_description/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_development_status/Special%3ABrowse\/Property%3AHas_development_status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_download_URL/Special%3ABrowse\/Property%3AHas_download_URL/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_input_format/Special%3ABrowse\/Property%3AHas_input_format/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_licence/Special%3ABrowse\/Property%3AHas_licence/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_logo/Special%3ABrowse\/Property%3AHas_logo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_output_format/Special%3ABrowse\/Property%3AHas_output_format/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_software_maturity_status/Special%3ABrowse\/Property%3AHas_software_maturity_status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_software_prerequisite/Special%3ABrowse\/Property%3AHas_software_prerequisite/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_subobject/Special%3ABrowse\/Property%3AHas_subobject/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_support_status/Special%3ABrowse\/Property%3AHas_support_status/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_title/Special%3ABrowse\/Property%3AHas_title/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_topic/Special%3ABrowse\/Property%3AHas_topic/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_type/Special%3ABrowse\/Property%3AHas_type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Has_website/Special%3ABrowse\/Property%3AHas_website/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Interaction-20type/Special%3ABrowse\/Property%3AInteraction-20type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Interaction_type/Special%3ABrowse\/Property%3AInteraction_type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Interacts-20with/Special%3ABrowse\/Property%3AInteracts-20with/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Interacts_with/Special%3ABrowse\/Property%3AInteracts_with/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Is-20open-20source/Special%3ABrowse\/Property%3AIs-20open-20source/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Is_open_source/Special%3ABrowse\/Property%3AIs_open_source/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Link-20type/Special%3ABrowse\/Property%3ALink-20type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Link_type/Special%3ABrowse\/Property%3ALink_type/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Linktitle/Special%3ABrowse\/Property%3ALinktitle/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Linktype/Special%3ABrowse\/Property%3ALinktype/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Release-20date/Special%3ABrowse\/Property%3ARelease-20date/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Release_date/Special%3ABrowse\/Property%3ARelease_date/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Subject/Special%3ABrowse\/Property%3ASubject/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Tool-20functionality-20or-20classification/Special%3ABrowse\/Property%3ATool-20functionality-20or-20classification/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Tool_functionality_or_classification/Special%3ABrowse\/Property%3ATool_functionality_or_classification/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Written-20in-20language/Special%3ABrowse\/Property%3AWritten-20in-20language/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Property:Written_in_language/Special%3ABrowse\/Property%3AWritten_in_language/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Textpresso-23http:-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide/Special%3ABrowse\/Textpresso-23http%3A-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Textpresso-23http:-2F-2Ftextpresso.org-2Fdownloads.html/Special%3ABrowse\/Textpresso-23http%3A-2F-2Ftextpresso.org-2Fdownloads.html/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Textpresso-23http:-2F-2Ftextpresso.org/Special%3ABrowse\/Textpresso-23http%3A-2F-2Ftextpresso.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Textpresso-23http:-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F/Special%3ABrowse\/Textpresso-23http%3A-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Textpresso-23http:-2F-2Fwhis.caltech.edu-2Ftextpresso-2F/Special%3ABrowse\/Textpresso-23http%3A-2F-2Fwhis.caltech.edu-2Ftextpresso-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Textpresso-23http:-2F-2Fwww.textpresso.org-2Fcelegans-2F/Special%3ABrowse\/Textpresso-23http%3A-2F-2Fwww.textpresso.org-2Fcelegans-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Tripal-23http:-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation/Special%3ABrowse\/Tripal-23http%3A-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/Tripal-23http:-2F-2Ftripal.info/Special%3ABrowse\/Tripal-23http%3A-2F-2Ftripal.info/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Alexkalderimis/Special%3ABrowse\/User%3AAlexkalderimis/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Alpapan/Special%3ABrowse\/User%3AAlpapan/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Baranda/Special%3ABrowse\/User%3ABaranda/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Bilardi/Special%3ABrowse\/User%3ABilardi/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Bmoore/Special%3ABrowse\/User%3ABmoore/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Bosborne/Special%3ABrowse\/User%3ABosborne/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Brianfoley/Special%3ABrowse\/User%3ABrianfoley/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Buggy/Special%3ABrowse\/User%3ABuggy/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Carsonholt/Special%3ABrowse\/User%3ACarsonholt/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Chemmeri/Special%3ABrowse\/User%3AChemmeri/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Childers/Special%3ABrowse\/User%3AChilders/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Chinmay/Special%3ABrowse\/User%3AChinmay/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Cjfields/Special%3ABrowse\/User%3ACjfields/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Clements/Special%3ABrowse\/User%3AClements/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Colin_Diesh/Special%3ABrowse\/User%3AColin_Diesh/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Dan/Special%3ABrowse\/User%3ADan/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:DanB/Special%3ABrowse\/User%3ADanB/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:DanBolser/Special%3ABrowse\/User%3ADanBolser/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:DanielRenfro/Special%3ABrowse\/User%3ADanielRenfro/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Dongilbert/Special%3ABrowse\/User%3ADongilbert/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Dukeleto/Special%3ABrowse\/User%3ADukeleto/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Elee/Special%3ABrowse\/User%3AElee/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Eric.ganko/Special%3ABrowse\/User%3AEric.ganko/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Eric_Rasche/Special%3ABrowse\/User%3AEric_Rasche/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:ErickAntezana/Special%3ABrowse\/User%3AErickAntezana/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Faga/Special%3ABrowse\/User%3AFaga/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Garrett/Special%3ABrowse\/User%3AGarrett/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Girlwithglasses-2FTemplate:StandardToolDisplay/Special%3ABrowse\/User%3AGirlwithglasses-2FTemplate%3AStandardToolDisplay/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Girlwithglasses-2FTemplate:ToolData-2Fgbrowse/Special%3ABrowse\/User%3AGirlwithglasses-2FTemplate%3AToolData-2Fgbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Girlwithglasses-2FTemplate:ToolData-2Fgbrowse_syn/Special%3ABrowse\/User%3AGirlwithglasses-2FTemplate%3AToolData-2Fgbrowse_syn/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Girlwithglasses-2FTemplate:ToolData-2Fgeneric/Special%3ABrowse\/User%3AGirlwithglasses-2FTemplate%3AToolData-2Fgeneric/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Girlwithglasses/Special%3ABrowse\/User%3AGirlwithglasses/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:GreggHelt2/Special%3ABrowse\/User%3AGreggHelt2/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Hlapp/Special%3ABrowse\/User%3AHlapp/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:JWarren/Special%3ABrowse\/User%3AJWarren/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:JamesTaylor/Special%3ABrowse\/User%3AJamesTaylor/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Jhannah/Special%3ABrowse\/User%3AJhannah/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:JimHu-2FGbrowse/Special%3ABrowse\/User%3AJimHu-2FGbrowse/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:JimHu/Special%3ABrowse\/User%3AJimHu/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Jogoodma/Special%3ABrowse\/User%3AJogoodma/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Jorvis/Special%3ABrowse\/User%3AJorvis/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:JunZhao/Special%3ABrowse\/User%3AJunZhao/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Junjun/Special%3ABrowse\/User%3AJunjun/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Justaddcoffee/Special%3ABrowse\/User%3AJustaddcoffee/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Lstein/Special%3ABrowse\/User%3ALstein/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Mara_Kim/Special%3ABrowse\/User%3AMara_Kim/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Mcaudy/Special%3ABrowse\/User%3AMcaudy/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Mckays/Special%3ABrowse\/User%3AMckays/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Mestato/Special%3ABrowse\/User%3AMestato/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Michael_Campbell/Special%3ABrowse\/User%3AMichael_Campbell/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:MitchSkinner/Special%3ABrowse\/User%3AMitchSkinner/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Mnrusimh/Special%3ABrowse\/User%3AMnrusimh/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Moni/Special%3ABrowse\/User%3AMoni/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:NLWashington/Special%3ABrowse\/User%3ANLWashington/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:NaamaMenda/Special%3ABrowse\/User%3ANaamaMenda/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:RBuels/Special%3ABrowse\/User%3ARBuels/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:RSCummings/Special%3ABrowse\/User%3ARSCummings/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Richard_Hayes/Special%3ABrowse\/User%3ARichard_Hayes/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:RobertBuels/Special%3ABrowse\/User%3ARobertBuels/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Robin.haw/Special%3ABrowse\/User%3ARobin.haw/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:RobinHouston/Special%3ABrowse\/User%3ARobinHouston/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Rsmith/Special%3ABrowse\/User%3ARsmith/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Russellsmithies/Special%3ABrowse\/User%3ARussellsmithies/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Scott/Special%3ABrowse\/User%3AScott/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Sficklin/Special%3ABrowse\/User%3ASficklin/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Sivam/Special%3ABrowse\/User%3ASivam/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Sperling/Special%3ABrowse\/User%3ASperling/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Stajich/Special%3ABrowse\/User%3AStajich/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Stevef/Special%3ABrowse\/User%3AStevef/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Stewarta/Special%3ABrowse\/User%3AStewarta/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Sundaram/Special%3ABrowse\/User%3ASundaram/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:SyedHaider/Special%3ABrowse\/User%3ASyedHaider/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Tharris/Special%3ABrowse\/User%3ATharris/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:TimCarver/Special%3ABrowse\/User%3ATimCarver/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Tjvision/Special%3ABrowse\/User%3ATjvision/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Xshi/Special%3ABrowse\/User%3AXshi/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/User:Ybendana/Special%3ABrowse\/User%3AYbendana/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo-23http:-2F-2Fcode.google.com-2Fp-2Fgenomancer/Special%3ABrowse\/WebApollo-23http%3A-2F-2Fcode.google.com-2Fp-2Fgenomancer/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo-23http:-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F/Special%3ABrowse\/WebApollo-23http%3A-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo-23http:-2F-2Fgenomearchitect.org/Special%3ABrowse\/WebApollo-23http%3A-2F-2Fgenomearchitect.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo-23http:-2F-2Fgenomearchitect.org:8080-2FWebApolloDemo-2F/Special%3ABrowse\/WebApollo-23http%3A-2F-2Fgenomearchitect.org%3A8080-2FWebApolloDemo-2F/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo-23https:-2F-2Fgithub.com-2Fgmod-2Fapollo/Special%3ABrowse\/WebApollo-23https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo2-23http:-2F-2Fgenomearchitect.org/Special%3ABrowse\/WebApollo2-23http%3A-2F-2Fgenomearchitect.org/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo2-23http:-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex/Special%3ABrowse\/WebApollo2-23http%3A-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo2-23https:-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases/Special%3ABrowse\/WebApollo2-23https%3A-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebApollo2-23https:-2F-2Fgithub.com-2Fgmod-2Fapollo/Special%3ABrowse\/WebApollo2-23https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebGBrowse-23http:-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html/Special%3ABrowse\/WebGBrowse-23http%3A-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/WebGBrowse-23http:-2F-2Fwebgbrowse.cgb.indiana.edu/Special%3ABrowse\/WebGBrowse-23http%3A-2F-2Fwebgbrowse.cgb.indiana.edu/smg' */*/*/*
perl -pi -e 'BEGIN{undef $/;} s/Special%3ABrowse\/XORT-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F/Special%3ABrowse\/XORT-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F/smg' */*/*/*
