git mv Special%3ABrowse/Apollo-2DChado_Integration_at_BovineBase:_Bugs_and_Suggestions.md Special%3ABrowse/Apollo-2DChado_Integration_at_BovineBase%3A_Bugs_and_Suggestions.md
git mv Special%3ABrowse/BLAST-20Graphic-20Viewer-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F.md Special%3ABrowse/BLAST-20Graphic-20Viewer-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F.md
git mv Special%3ABrowse/BLAST-20Graphic-20Viewer-23http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl.md Special%3ABrowse/BLAST-20Graphic-20Viewer-23http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl.md
git mv Special%3ABrowse/Bio::Chado::Schema.md Special%3ABrowse/Bio%3A%3AChado%3A%3ASchema.md
git mv Special%3ABrowse/Bio::GMOD.md Special%3ABrowse/Bio%3A%3AGMOD.md
git mv Special%3ABrowse/BioGraphics:vista_plot_glyph.md Special%3ABrowse/BioGraphics%3Avista_plot_glyph.md
git mv Special%3ABrowse/BioMart-23http:-2F-2Fwww.biomart.org-2F.md Special%3ABrowse/BioMart-23http%3A-2F-2Fwww.biomart.org-2F.md
git mv Special%3ABrowse/BioMart-23http:-2F-2Fwww.biomart.org-2Fcommunity.html.md Special%3ABrowse/BioMart-23http%3A-2F-2Fwww.biomart.org-2Fcommunity.html.md
git mv Special%3ABrowse/BioMart-23http:-2F-2Fwww.biomart.org-2Fdownload.html.md Special%3ABrowse/BioMart-23http%3A-2F-2Fwww.biomart.org-2Fdownload.html.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fbioinf.scri.sari.ac.uk-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fbioinf.scri.sari.ac.uk-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi.md Special%3ABrowse/CMap-23http%3A-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md Special%3ABrowse/CMap-23http%3A-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md Special%3ABrowse/CMap-23http%3A-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fmap.lab.nig.ac.jp:8080-2Fcmap-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fmap.lab.nig.ac.jp%3A8080-2Fcmap-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fmedvet.angis.org.au-2Fcmap-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fmedvet.angis.org.au-2Fcmap-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer.md Special%3ABrowse/CMap-23http%3A-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer.md
git mv Special%3ABrowse/CMap-23http:-2F-2Frye.pw.usda.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info-3Fmap_set_aid=Barley_consensus_2003.md Special%3ABrowse/CMap-23http%3A-2F-2Frye.pw.usda.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info-3Fmap_set_aid=Barley_consensus_2003.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fsoybeanbreederstoolbox.org-2Findex.php.md Special%3ABrowse/CMap-23http%3A-2F-2Fsoybeanbreederstoolbox.org-2Findex.php.md
git mv Special%3ABrowse/CMap-23http:-2F-2Ftropgenedb.cirad.fr.md Special%3ABrowse/CMap-23http%3A-2F-2Ftropgenedb.cirad.fr.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.bioinfo.wsu.edu-2Fcgi-2Dbin-2Fgdr-2Fcmap-2Fmap_set_info-3Fmap_set_aid=17.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.bioinfo.wsu.edu-2Fcgi-2Dbin-2Fgdr-2Fcmap-2Fmap_set_info-3Fmap_set_aid=17.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.comparative-2Dlegumes.org-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.comparative-2Dlegumes.org-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.cottondb.org-2Fcmap-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.cottondb.org-2Fcmap-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.cottonmarker.org-2F.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.cottonmarker.org-2F.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.gramene.org-2Fcmap.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.gramene.org-2Fcmap.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.gramene.org-2Fdb-2Fcmap.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.gramene.org-2Fdb-2Fcmap.md
git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM;ref_map_aids=109.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM;ref_map_aids=109.md
git mv Special%3ABrowse/CMap-23https:-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap.md Special%3ABrowse/CMap-23https%3A-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap.md
git mv Special%3ABrowse/Canto-23http:-2F-2Fcuration.pombase.org-2F.md Special%3ABrowse/Canto-23http%3A-2F-2Fcuration.pombase.org-2F.md
git mv Special%3ABrowse/Canto-23http:-2F-2Fcuration.pombase.org-2Fdemo.md Special%3ABrowse/Canto-23http%3A-2F-2Fcuration.pombase.org-2Fdemo.md
git mv Special%3ABrowse/Canto-23http:-2F-2Fcuration.pombase.org-2Fpombe.md Special%3ABrowse/Canto-23http%3A-2F-2Fcuration.pombase.org-2Fpombe.md
git mv Special%3ABrowse/Canto-23http:-2F-2Fcuration.pombase.org-2Funiprot.md Special%3ABrowse/Canto-23http%3A-2F-2Fcuration.pombase.org-2Funiprot.md
git mv Special%3ABrowse/Canto-23https:-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin.md Special%3ABrowse/Canto-23https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin.md
git mv Special%3ABrowse/Canto-23https:-2F-2Fgithub.com-2Fpombase-2Fcanto.md Special%3ABrowse/Canto-23https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto.md
git mv Special%3ABrowse/Category:!FixAfterUpgrade.md Special%3ABrowse/Category%3A!FixAfterUpgrade.md
git mv Special%3ABrowse/Category:!Lacking_ERD.md Special%3ABrowse/Category%3A!Lacking_ERD.md
git mv Special%3ABrowse/Category:2011_Spring_Training.md Special%3ABrowse/Category%3A2011_Spring_Training.md
git mv Special%3ABrowse/Category:2012_Summer_School.md Special%3ABrowse/Category%3A2012_Summer_School.md
git mv Special%3ABrowse/Category:2013_Summer_School.md Special%3ABrowse/Category%3A2013_Summer_School.md
git mv Special%3ABrowse/Category:AJAX.md Special%3ABrowse/Category%3AAJAX.md
git mv Special%3ABrowse/Category:Analysis.md Special%3ABrowse/Category%3AAnalysis.md
git mv Special%3ABrowse/Category:Annotation.md Special%3ABrowse/Category%3AAnnotation.md
git mv Special%3ABrowse/Category:ApiDB.md Special%3ABrowse/Category%3AApiDB.md
git mv Special%3ABrowse/Category:Apollo.md Special%3ABrowse/Category%3AApollo.md
git mv Special%3ABrowse/Category:BLAST.md Special%3ABrowse/Category%3ABLAST.md
git mv Special%3ABrowse/Category:BioDIG.md Special%3ABrowse/Category%3ABioDIG.md
git mv Special%3ABrowse/Category:BioMart.md Special%3ABrowse/Category%3ABioMart.md
git mv Special%3ABrowse/Category:BioPerl.md Special%3ABrowse/Category%3ABioPerl.md
git mv Special%3ABrowse/Category:Biology.md Special%3ABrowse/Category%3ABiology.md
git mv Special%3ABrowse/Category:CMap.md Special%3ABrowse/Category%3ACMap.md
git mv Special%3ABrowse/Category:Canto.md Special%3ABrowse/Category%3ACanto.md
git mv Special%3ABrowse/Category:Categories.md Special%3ABrowse/Category%3ACategories.md
git mv Special%3ABrowse/Category:Chado.md Special%3ABrowse/Category%3AChado.md
git mv Special%3ABrowse/Category:Chado_FlyBase.md Special%3ABrowse/Category%3AChado_FlyBase.md
git mv Special%3ABrowse/Category:Chado_Modules.md Special%3ABrowse/Category%3AChado_Modules.md
git mv Special%3ABrowse/Category:Chado_Presentations.md Special%3ABrowse/Category%3AChado_Presentations.md
git mv Special%3ABrowse/Category:Cloud.md Special%3ABrowse/Category%3ACloud.md
git mv Special%3ABrowse/Category:Community_Annotation.md Special%3ABrowse/Category%3ACommunity_Annotation.md
git mv Special%3ABrowse/Category:Comparative_Genomics.md Special%3ABrowse/Category%3AComparative_Genomics.md
git mv Special%3ABrowse/Category:Computing.md Special%3ABrowse/Category%3AComputing.md
git mv Special%3ABrowse/Category:Conferences.md Special%3ABrowse/Category%3AConferences.md
git mv Special%3ABrowse/Category:Configuration.md Special%3ABrowse/Category%3AConfiguration.md
git mv Special%3ABrowse/Category:DAS.md Special%3ABrowse/Category%3ADAS.md
git mv Special%3ABrowse/Category:Database.md Special%3ABrowse/Category%3ADatabase.md
git mv Special%3ABrowse/Category:Database_Tools.md Special%3ABrowse/Category%3ADatabase_Tools.md
git mv Special%3ABrowse/Category:Deprecated.md Special%3ABrowse/Category%3ADeprecated.md
git mv Special%3ABrowse/Category:DictyBase.md Special%3ABrowse/Category%3ADictyBase.md
git mv Special%3ABrowse/Category:Documentation.md Special%3ABrowse/Category%3ADocumentation.md
git mv Special%3ABrowse/Category:Drupal.md Special%3ABrowse/Category%3ADrupal.md
git mv Special%3ABrowse/Category:ERD.md Special%3ABrowse/Category%3AERD.md
git mv Special%3ABrowse/Category:Education_and_Outreach.md Special%3ABrowse/Category%3AEducation_and_Outreach.md
git mv Special%3ABrowse/Category:Ergatis.md Special%3ABrowse/Category%3AErgatis.md
git mv Special%3ABrowse/Category:Events.md Special%3ABrowse/Category%3AEvents.md
git mv Special%3ABrowse/Category:Evolution.md Special%3ABrowse/Category%3AEvolution.md
git mv Special%3ABrowse/Category:Expression.md Special%3ABrowse/Category%3AExpression.md
git mv Special%3ABrowse/Category:External.md Special%3ABrowse/Category%3AExternal.md
git mv Special%3ABrowse/Category:FAQ.md Special%3ABrowse/Category%3AFAQ.md
git mv Special%3ABrowse/Category:File_Formats.md Special%3ABrowse/Category%3AFile_Formats.md
git mv Special%3ABrowse/Category:FlyBase.md Special%3ABrowse/Category%3AFlyBase.md
git mv Special%3ABrowse/Category:GBrowse.md Special%3ABrowse/Category%3AGBrowse.md
git mv Special%3ABrowse/Category:GBrowse_2.md Special%3ABrowse/Category%3AGBrowse_2.md
git mv Special%3ABrowse/Category:GBrowse_Developer.md Special%3ABrowse/Category%3AGBrowse_Developer.md
git mv Special%3ABrowse/Category:GBrowse_Plugins.md Special%3ABrowse/Category%3AGBrowse_Plugins.md
git mv Special%3ABrowse/Category:GBrowse_syn.md Special%3ABrowse/Category%3AGBrowse_syn.md
git mv Special%3ABrowse/Category:GFF.md Special%3ABrowse/Category%3AGFF.md
git mv Special%3ABrowse/Category:GFF3.md Special%3ABrowse/Category%3AGFF3.md
git mv Special%3ABrowse/Category:GMOD-20Component.md Special%3ABrowse/Category%3AGMOD-20Component.md
git mv Special%3ABrowse/Category:GMOD-20Tools.md Special%3ABrowse/Category%3AGMOD-20Tools.md
git mv Special%3ABrowse/Category:GMODWeb.md Special%3ABrowse/Category%3AGMODWeb.md
git mv Special%3ABrowse/Category:GMOD_Best_Practices.md Special%3ABrowse/Category%3AGMOD_Best_Practices.md
git mv Special%3ABrowse/Category:GMOD_Community.md Special%3ABrowse/Category%3AGMOD_Community.md
git mv Special%3ABrowse/Category:GMOD_Component.md Special%3ABrowse/Category%3AGMOD_Component.md
git mv Special%3ABrowse/Category:GMOD_Components.md Special%3ABrowse/Category%3AGMOD_Components.md
git mv Special%3ABrowse/Category:GMOD_Developers.md Special%3ABrowse/Category%3AGMOD_Developers.md
git mv Special%3ABrowse/Category:GMOD_Evo_Hackathon.md Special%3ABrowse/Category%3AGMOD_Evo_Hackathon.md
git mv Special%3ABrowse/Category:GMOD_Online_Training.md Special%3ABrowse/Category%3AGMOD_Online_Training.md
git mv Special%3ABrowse/Category:GMOD_Project.md Special%3ABrowse/Category%3AGMOD_Project.md
git mv Special%3ABrowse/Category:GMOD_Project_Logos.md Special%3ABrowse/Category%3AGMOD_Project_Logos.md
git mv Special%3ABrowse/Category:GMOD_Project_Presentations.md Special%3ABrowse/Category%3AGMOD_Project_Presentations.md
git mv Special%3ABrowse/Category:GMOD_Schools.md Special%3ABrowse/Category%3AGMOD_Schools.md
git mv Special%3ABrowse/Category:GMOD_Tools.md Special%3ABrowse/Category%3AGMOD_Tools.md
git mv Special%3ABrowse/Category:GMOD_Web_Site.md Special%3ABrowse/Category%3AGMOD_Web_Site.md
git mv Special%3ABrowse/Category:GMOD_in_the_Cloud.md Special%3ABrowse/Category%3AGMOD_in_the_Cloud.md
git mv Special%3ABrowse/Category:GMOD_virtual_server.md Special%3ABrowse/Category%3AGMOD_virtual_server.md
git mv Special%3ABrowse/Category:GSoC.md Special%3ABrowse/Category%3AGSoC.md
git mv Special%3ABrowse/Category:Galaxy.md Special%3ABrowse/Category%3AGalaxy.md
git mv Special%3ABrowse/Category:Generic_Gene_Pages.md Special%3ABrowse/Category%3AGeneric_Gene_Pages.md
git mv Special%3ABrowse/Category:Gramene.md Special%3ABrowse/Category%3AGramene.md
git mv Special%3ABrowse/Category:HOWTO.md Special%3ABrowse/Category%3AHOWTO.md
git mv Special%3ABrowse/Category:Help.md Special%3ABrowse/Category%3AHelp.md
git mv Special%3ABrowse/Category:IGS.md Special%3ABrowse/Category%3AIGS.md
git mv Special%3ABrowse/Category:Install.md Special%3ABrowse/Category%3AInstall.md
git mv Special%3ABrowse/Category:InterMine.md Special%3ABrowse/Category%3AInterMine.md
git mv Special%3ABrowse/Category:JBrowse.md Special%3ABrowse/Category%3AJBrowse.md
git mv Special%3ABrowse/Category:Java.md Special%3ABrowse/Category%3AJava.md
git mv Special%3ABrowse/Category:Javascript.md Special%3ABrowse/Category%3AJavascript.md
git mv Special%3ABrowse/Category:Jobs.md Special%3ABrowse/Category%3AJobs.md
git mv Special%3ABrowse/Category:Linux.md Special%3ABrowse/Category%3ALinux.md
git mv Special%3ABrowse/Category:Logos_and_Icons.md Special%3ABrowse/Category%3ALogos_and_Icons.md
git mv Special%3ABrowse/Category:LuceGene.md Special%3ABrowse/Category%3ALuceGene.md
git mv Special%3ABrowse/Category:MAKER.md Special%3ABrowse/Category%3AMAKER.md
git mv Special%3ABrowse/Category:MGI.md Special%3ABrowse/Category%3AMGI.md
git mv Special%3ABrowse/Category:MOD_UI_Presentations.md Special%3ABrowse/Category%3AMOD_UI_Presentations.md
git mv Special%3ABrowse/Category:MOD_User_Interfaces.md Special%3ABrowse/Category%3AMOD_User_Interfaces.md
git mv Special%3ABrowse/Category:Mac_OS_X.md Special%3ABrowse/Category%3AMac_OS_X.md
git mv Special%3ABrowse/Category:Meetings.md Special%3ABrowse/Category%3AMeetings.md
git mv Special%3ABrowse/Category:Member_Logos.md Special%3ABrowse/Category%3AMember_Logos.md
git mv Special%3ABrowse/Category:Microarrays.md Special%3ABrowse/Category%3AMicroarrays.md
git mv Special%3ABrowse/Category:Middleware.md Special%3ABrowse/Category%3AMiddleware.md
git mv Special%3ABrowse/Category:Middleware_Presentations.md Special%3ABrowse/Category%3AMiddleware_Presentations.md
git mv Special%3ABrowse/Category:Modware.md Special%3ABrowse/Category%3AModware.md
git mv Special%3ABrowse/Category:MySQL.md Special%3ABrowse/Category%3AMySQL.md
git mv Special%3ABrowse/Category:NGS.md Special%3ABrowse/Category%3ANGS.md
git mv Special%3ABrowse/Category:Natural_Diversity.md Special%3ABrowse/Category%3ANatural_Diversity.md
git mv Special%3ABrowse/Category:Needs_Editing.md Special%3ABrowse/Category%3ANeeds_Editing.md
git mv Special%3ABrowse/Category:Needs_Testing.md Special%3ABrowse/Category%3ANeeds_Testing.md
git mv Special%3ABrowse/Category:News_Items.md Special%3ABrowse/Category%3ANews_Items.md
git mv Special%3ABrowse/Category:Ontologies.md Special%3ABrowse/Category%3AOntologies.md
git mv Special%3ABrowse/Category:Pages_containing_blacklisted_links.md Special%3ABrowse/Category%3APages_containing_blacklisted_links.md
git mv Special%3ABrowse/Category:Pages_with_broken_file_links.md Special%3ABrowse/Category%3APages_with_broken_file_links.md
git mv Special%3ABrowse/Category:Pages_with_problems_or_questions.md Special%3ABrowse/Category%3APages_with_problems_or_questions.md
git mv Special%3ABrowse/Category:Paper_Cuts.md Special%3ABrowse/Category%3APaper_Cuts.md
git mv Special%3ABrowse/Category:ParameciumDB.md Special%3ABrowse/Category%3AParameciumDB.md
git mv Special%3ABrowse/Category:Pathway_Tools.md Special%3ABrowse/Category%3APathway_Tools.md
git mv Special%3ABrowse/Category:Performance.md Special%3ABrowse/Category%3APerformance.md
git mv Special%3ABrowse/Category:Perl.md Special%3ABrowse/Category%3APerl.md
git mv Special%3ABrowse/Category:Phenotypes.md Special%3ABrowse/Category%3APhenotypes.md
git mv Special%3ABrowse/Category:Posters.md Special%3ABrowse/Category%3APosters.md
git mv Special%3ABrowse/Category:PostgreSQL.md Special%3ABrowse/Category%3APostgreSQL.md
git mv Special%3ABrowse/Category:Presentations.md Special%3ABrowse/Category%3APresentations.md
git mv Special%3ABrowse/Category:Proposals.md Special%3ABrowse/Category%3AProposals.md
git mv Special%3ABrowse/Category:PubSearch.md Special%3ABrowse/Category%3APubSearch.md
git mv Special%3ABrowse/Category:Publications.md Special%3ABrowse/Category%3APublications.md
git mv Special%3ABrowse/Category:REST.md Special%3ABrowse/Category%3AREST.md
git mv Special%3ABrowse/Category:RGD.md Special%3ABrowse/Category%3ARGD.md
git mv Special%3ABrowse/Category:RPC.md Special%3ABrowse/Category%3ARPC.md
git mv Special%3ABrowse/Category:Rails.md Special%3ABrowse/Category%3ARails.md
git mv Special%3ABrowse/Category:Reactome.md Special%3ABrowse/Category%3AReactome.md
git mv Special%3ABrowse/Category:SAMtools.md Special%3ABrowse/Category%3ASAMtools.md
git mv Special%3ABrowse/Category:SGD.md Special%3ABrowse/Category%3ASGD.md
git mv Special%3ABrowse/Category:SGN.md Special%3ABrowse/Category%3ASGN.md
git mv Special%3ABrowse/Category:SOBA.md Special%3ABrowse/Category%3ASOBA.md
git mv Special%3ABrowse/Category:Screenshots.md Special%3ABrowse/Category%3AScreenshots.md
git mv Special%3ABrowse/Category:SemanticLink.md Special%3ABrowse/Category%3ASemanticLink.md
git mv Special%3ABrowse/Category:Semantic_web.md Special%3ABrowse/Category%3ASemantic_web.md
git mv Special%3ABrowse/Category:Session.md Special%3ABrowse/Category%3ASession.md
git mv Special%3ABrowse/Category:Social_Media.md Special%3ABrowse/Category%3ASocial_Media.md
git mv Special%3ABrowse/Category:Software_Engineer.md Special%3ABrowse/Category%3ASoftware_Engineer.md
git mv Special%3ABrowse/Category:Sybil.md Special%3ABrowse/Category%3ASybil.md
git mv Special%3ABrowse/Category:TAIR.md Special%3ABrowse/Category%3ATAIR.md
git mv Special%3ABrowse/Category:TableEdit.md Special%3ABrowse/Category%3ATableEdit.md
git mv Special%3ABrowse/Category:Template.md Special%3ABrowse/Category%3ATemplate.md
git mv Special%3ABrowse/Category:Textpresso.md Special%3ABrowse/Category%3ATextpresso.md
git mv Special%3ABrowse/Category:Tool_data.md Special%3ABrowse/Category%3ATool_data.md
git mv Special%3ABrowse/Category:Tools_using_GMOD.md Special%3ABrowse/Category%3ATools_using_GMOD.md
git mv Special%3ABrowse/Category:Tripal.md Special%3ABrowse/Category%3ATripal.md
git mv Special%3ABrowse/Category:Turnkey.md Special%3ABrowse/Category%3ATurnkey.md
git mv Special%3ABrowse/Category:Tutorial.md Special%3ABrowse/Category%3ATutorial.md
git mv Special%3ABrowse/Category:Tutorials.md Special%3ABrowse/Category%3ATutorials.md
git mv Special%3ABrowse/Category:Under_Construction.md Special%3ABrowse/Category%3AUnder_Construction.md
git mv Special%3ABrowse/Category:Unsupported.md Special%3ABrowse/Category%3AUnsupported.md
git mv Special%3ABrowse/Category:User_Experiences.md Special%3ABrowse/Category%3AUser_Experiences.md
git mv Special%3ABrowse/Category:Users.md Special%3ABrowse/Category%3AUsers.md
git mv Special%3ABrowse/Category:Visualization.md Special%3ABrowse/Category%3AVisualization.md
git mv Special%3ABrowse/Category:WFleaBase.md Special%3ABrowse/Category%3AWFleaBase.md
git mv Special%3ABrowse/Category:WebGBrowse.md Special%3ABrowse/Category%3AWebGBrowse.md
git mv Special%3ABrowse/Category:Web_services.md Special%3ABrowse/Category%3AWeb_services.md
git mv Special%3ABrowse/Category:Webapollo-2Dminutes.md Special%3ABrowse/Category%3AWebapollo-2Dminutes.md
git mv Special%3ABrowse/Category:Webapollo.md Special%3ABrowse/Category%3AWebapollo.md
git mv Special%3ABrowse/Category:Wiki_Tools.md Special%3ABrowse/Category%3AWiki_Tools.md
git mv Special%3ABrowse/Category:Windows.md Special%3ABrowse/Category%3AWindows.md
git mv Special%3ABrowse/Category:WormBase.md Special%3ABrowse/Category%3AWormBase.md
git mv Special%3ABrowse/Category:XML.md Special%3ABrowse/Category%3AXML.md
git mv Special%3ABrowse/Category:XORT.md Special%3ABrowse/Category%3AXORT.md
git mv Special%3ABrowse/Chado-23https:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fgmod-2F.md Special%3ABrowse/Chado-23https%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fgmod-2F.md
git mv Special%3ABrowse/Chado::AutoDBI.md Special%3ABrowse/Chado%3A%3AAutoDBI.md
git mv Special%3ABrowse/Chado::AutoDBI_Presentation.md Special%3ABrowse/Chado%3A%3AAutoDBI_Presentation.md
git mv Special%3ABrowse/DBD::mysql_on_the_Mac.md Special%3ABrowse/DBD%3A%3Amysql_on_the_Mac.md
git mv Special%3ABrowse/DIYA-23https:-2F-2Fgithub.com-2Fbioteam-2FDIYA.md Special%3ABrowse/DIYA-23https%3A-2F-2Fgithub.com-2Fbioteam-2FDIYA.md
git mv Special%3ABrowse/Databases:_Primary,_Foreign_and_Alternate_Keys.md Special%3ABrowse/Databases%3A_Primary,_Foreign_and_Alternate_Keys.md
git mv Special%3ABrowse/Databases:_Tables,_Rows,_and_Columns.md Special%3ABrowse/Databases%3A_Tables,_Rows,_and_Columns.md
git mv Special%3ABrowse/Face_Caucus_ApiDB:_User_Studies_and_Impact_on_Development.md Special%3ABrowse/Face_Caucus_ApiDB%3A_User_Studies_and_Impact_on_Development.md
git mv Special%3ABrowse/Face_Caucus_SGN:_Associating_Solanaceae_loci_with_phenotype.md Special%3ABrowse/Face_Caucus_SGN%3A_Associating_Solanaceae_loci_with_phenotype.md
git mv Special%3ABrowse/Face_Caucus_UCSC:_User_Interface_Issues.md Special%3ABrowse/Face_Caucus_UCSC%3A_User_Interface_Issues.md
git mv Special%3ABrowse/GBrowse-20syn-23http:-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele;name=X:1050001..1150000.md Special%3ABrowse/GBrowse-20syn-23http%3A-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele;name=X%3A1050001..1150000.md
git mv Special%3ABrowse/GBrowse-20syn-23http:-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri;name=chrX:620000..670000.md Special%3ABrowse/GBrowse-20syn-23http%3A-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri;name=chrX%3A620000..670000.md
git mv Special%3ABrowse/GBrowse-20syn-23http:-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F.md Special%3ABrowse/GBrowse-20syn-23http%3A-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F.md
git mv Special%3ABrowse/GBrowse-20syn-23http:-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501.md Special%3ABrowse/GBrowse-20syn-23http%3A-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501.md
git mv Special%3ABrowse/GBrowse-20syn-23https:-2F-2Fgithub.com-2FGMOD-2FGBrowse.md Special%3ABrowse/GBrowse-20syn-23https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse.md
git mv Special%3ABrowse/GBrowse-23http:-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel.md Special%3ABrowse/GBrowse-23http%3A-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel.md
git mv Special%3ABrowse/GBrowse-23http:-2F-2Fgbrowse.org.md Special%3ABrowse/GBrowse-23http%3A-2F-2Fgbrowse.org.md
git mv Special%3ABrowse/GBrowse-23http:-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse.md Special%3ABrowse/GBrowse-23http%3A-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse.md
git mv Special%3ABrowse/GBrowse-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F.md Special%3ABrowse/GBrowse-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F.md
git mv Special%3ABrowse/GBrowse-23http:-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F.md Special%3ABrowse/GBrowse-23http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F.md
git mv Special%3ABrowse/GBrowse-23https:-2F-2Fgithub.com-2FGMOD-2FGBrowse.md Special%3ABrowse/GBrowse-23https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse.md
git mv Special%3ABrowse/GMOD:About.md Special%3ABrowse/GMOD%3AAbout.md
git mv Special%3ABrowse/GO-20Graphic-20Viewer-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F.md Special%3ABrowse/GO-20Graphic-20Viewer-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F.md
git mv Special%3ABrowse/GO-20Graphic-20Viewer-23http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl.md Special%3ABrowse/GO-20Graphic-20Viewer-23http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl.md
git mv Special%3ABrowse/GO::TermFinder-23http:-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder.md Special%3ABrowse/GO%3A%3ATermFinder-23http%3A-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder.md
git mv Special%3ABrowse/GO::TermFinder-23http:-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F.md Special%3ABrowse/GO%3A%3ATermFinder-23http%3A-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F.md
git mv Special%3ABrowse/GO::TermFinder-2Ftool_data.md Special%3ABrowse/GO%3A%3ATermFinder-2Ftool_data.md
git mv Special%3ABrowse/GO::TermFinder.md Special%3ABrowse/GO%3A%3ATermFinder.md
git mv Special%3ABrowse/Galaxy-23http:-2F-2Fgetgalaxy.org-2F.md Special%3ABrowse/Galaxy-23http%3A-2F-2Fgetgalaxy.org-2F.md
git mv Special%3ABrowse/Galaxy-23http:-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers.md Special%3ABrowse/Galaxy-23http%3A-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Fdocs.galaxyproject.org.md Special%3ABrowse/Galaxy-23https%3A-2F-2Fdocs.galaxyproject.org.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Fgalaxyproject.github.io.md Special%3ABrowse/Galaxy-23https%3A-2F-2Fgalaxyproject.github.io.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Fgalaxyproject.org-2F.md Special%3ABrowse/Galaxy-23https%3A-2F-2Fgalaxyproject.org-2F.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Fgalaxyproject.org-2Fuse-2F.md Special%3ABrowse/Galaxy-23https%3A-2F-2Fgalaxyproject.org-2Fuse-2F.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F.md Special%3ABrowse/Galaxy-23https%3A-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Ftwitter.com-2Fgalaxyproject.md Special%3ABrowse/Galaxy-23https%3A-2F-2Ftwitter.com-2Fgalaxyproject.md
git mv Special%3ABrowse/Galaxy-23https:-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy.md Special%3ABrowse/Galaxy-23https%3A-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy.md
git mv Special%3ABrowse/Help:Editing.md Special%3ABrowse/Help%3AEditing.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fratmine.mcw.edu-2F.md Special%3ABrowse/InterMine-23http%3A-2F-2Fratmine.mcw.edu-2F.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fwww.flymine.org.md Special%3ABrowse/InterMine-23http%3A-2F-2Fwww.flymine.org.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fwww.intermine.org.md Special%3ABrowse/InterMine-23http%3A-2F-2Fwww.intermine.org.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fwww.mousemine.org-2F.md Special%3ABrowse/InterMine-23http%3A-2F-2Fwww.mousemine.org-2F.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine.md Special%3ABrowse/InterMine-23http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fyeastmine.yeastgenome.org-2F.md Special%3ABrowse/InterMine-23http%3A-2F-2Fyeastmine.yeastgenome.org-2F.md
git mv Special%3ABrowse/InterMine-23http:-2F-2Fzmine.zfin.org-2F.md Special%3ABrowse/InterMine-23http%3A-2F-2Fzmine.zfin.org-2F.md
git mv Special%3ABrowse/InterMine-23https:-2F-2Fgithub.com-2Fintermine-2Fintermine.git.md Special%3ABrowse/InterMine-23https%3A-2F-2Fgithub.com-2Fintermine-2Fintermine.git.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fbeetlebase.org.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fbeetlebase.org.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fgenomesunzipped.org-2Fjbrowse.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fgenomesunzipped.org-2Fjbrowse.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fgithub.com-2FGMOD-2Fjbrowse.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Ficemangenome.net-2F.md Special%3ABrowse/JBrowse-23http%3A-2F-2Ficemangenome.net-2F.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fjbrowse.org-2Fdemos.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fjbrowse.org-2Fdemos.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fjbrowse.org-2Finstall-2F.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fjbrowse.org-2Finstall-2F.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fjbrowse.org.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fjbrowse.org.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Ftwitter.com-2Fusejbrowse.md Special%3ABrowse/JBrowse-23http%3A-2F-2Ftwitter.com-2Fusejbrowse.md
git mv Special%3ABrowse/JBrowse-23http:-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F.md Special%3ABrowse/JBrowse-23http%3A-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F.md
git mv Special%3ABrowse/JBrowse2-23http:-2F-2Fjbrowse.org-2Fdemos.md Special%3ABrowse/JBrowse2-23http%3A-2F-2Fjbrowse.org-2Fdemos.md
git mv Special%3ABrowse/JBrowse2-23http:-2F-2Fjbrowse.org.md Special%3ABrowse/JBrowse2-23http%3A-2F-2Fjbrowse.org.md
git mv Special%3ABrowse/JBrowse2-23http:-2F-2Ftwitter.com-2Fusejbrowse.md Special%3ABrowse/JBrowse2-23http%3A-2F-2Ftwitter.com-2Fusejbrowse.md
git mv Special%3ABrowse/JBrowse2-23https:-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F.md Special%3ABrowse/JBrowse2-23https%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F.md
git mv Special%3ABrowse/JBrowse2-23https:-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web.md Special%3ABrowse/JBrowse2-23https%3A-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web.md
git mv Special%3ABrowse/LabDoc:_Generic_Laboratory_Protocol_Documentation_System.md Special%3ABrowse/LabDoc%3A_Generic_Laboratory_Protocol_Documentation_System.md
git mv Special%3ABrowse/MAKER-23http:-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi.md Special%3ABrowse/MAKER-23http%3A-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi.md
git mv Special%3ABrowse/MAKER-23http:-2F-2Fhymenopteragenome.org-2Fant_genomes-2F.md Special%3ABrowse/MAKER-23http%3A-2F-2Fhymenopteragenome.org-2Fant_genomes-2F.md
git mv Special%3ABrowse/MAKER-23http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html.md Special%3ABrowse/MAKER-23http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html.md
git mv Special%3ABrowse/MAKER-23http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html.md Special%3ABrowse/MAKER-23http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html.md
git mv Special%3ABrowse/MAKER-23http:-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi.md Special%3ABrowse/MAKER-23http%3A-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi.md
git mv Special%3ABrowse/MAKER-23https:-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48.md Special%3ABrowse/MAKER-23https%3A-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48.md
git mv Special%3ABrowse/MOD_User_Interfaces:_Sample_of_several_MOD_Top_Level_functions.md Special%3ABrowse/MOD_User_Interfaces%3A_Sample_of_several_MOD_Top_Level_functions.md
git mv Special%3ABrowse/MOD_User_Interfaces:_outline_of_topics.md Special%3ABrowse/MOD_User_Interfaces%3A_outline_of_topics.md
git mv Special%3ABrowse/News-2F2013_Meeting:_Keynote_Announcement.md Special%3ABrowse/News-2F2013_Meeting%3A_Keynote_Announcement.md
git mv Special%3ABrowse/News-2F2013_Meeting:_Last_Day_For_Early_Birds.md Special%3ABrowse/News-2F2013_Meeting%3A_Last_Day_For_Early_Birds.md
git mv Special%3ABrowse/News-2FBeta_Test_CMap:_Win_a_T-2DShirt!.md Special%3ABrowse/News-2FBeta_Test_CMap%3A_Win_a_T-2DShirt!.md
git mv Special%3ABrowse/News-2FBio::Chado::Schema_0.03_Released.md Special%3ABrowse/News-2FBio%3A%3AChado%3A%3ASchema_0.03_Released.md
git mv Special%3ABrowse/News-2FBio::Chado::Schema_0.05_Released.md Special%3ABrowse/News-2FBio%3A%3AChado%3A%3ASchema_0.05_Released.md
git mv Special%3ABrowse/News-2FCVS_to_SVN_Conversion:_Done.md Special%3ABrowse/News-2FCVS_to_SVN_Conversion%3A_Done.md
git mv Special%3ABrowse/News-2FCVS_to_SVN_Conversion:_Sept_15.md Special%3ABrowse/News-2FCVS_to_SVN_Conversion%3A_Sept_15.md
git mv Special%3ABrowse/News-2FChado_in_RDF:_OpenFlyData.md Special%3ABrowse/News-2FChado_in_RDF%3A_OpenFlyData.md
git mv Special%3ABrowse/News-2FDIYA:_Do_It_Yourself_Annotator.md Special%3ABrowse/News-2FDIYA%3A_Do_It_Yourself_Annotator.md
git mv Special%3ABrowse/News-2FFeedback_Wanted:_JBrowse_UI_Redesign.md Special%3ABrowse/News-2FFeedback_Wanted%3A_JBrowse_UI_Redesign.md
git mv Special%3ABrowse/News-2FGCC2013:_Register!_Present!.md Special%3ABrowse/News-2FGCC2013%3A_Register!_Present!.md
git mv Special%3ABrowse/News-2FGCC2014:_June_30_-2D_July_2.md Special%3ABrowse/News-2FGCC2014%3A_June_30_-2D_July_2.md
git mv Special%3ABrowse/News-2FGMOD:_Spread_the_Word!.md Special%3ABrowse/News-2FGMOD%3A_Spread_the_Word!.md
git mv Special%3ABrowse/News-2FGMOD_2014_San_Diego:_Save_the_Date.md Special%3ABrowse/News-2FGMOD_2014_San_Diego%3A_Save_the_Date.md
git mv Special%3ABrowse/News-2FGMOD_Americas:_March_2011.md Special%3ABrowse/News-2FGMOD_Americas%3A_March_2011.md
git mv Special%3ABrowse/News-2FGMOD_Meeting:_Sept._13-2D14.md Special%3ABrowse/News-2FGMOD_Meeting%3A_Sept._13-2D14.md
git mv Special%3ABrowse/News-2FGMOD_Nomination:_ISGA.md Special%3ABrowse/News-2FGMOD_Nomination%3A_ISGA.md
git mv Special%3ABrowse/News-2FGMOD_Spring_Training:_Apply_Now.md Special%3ABrowse/News-2FGMOD_Spring_Training%3A_Apply_Now.md
git mv Special%3ABrowse/News-2FGMOD_Summer_School_2012:_Apply_Now.md Special%3ABrowse/News-2FGMOD_Summer_School_2012%3A_Apply_Now.md
git mv Special%3ABrowse/News-2FGalaxy_Events:_April_2011.md Special%3ABrowse/News-2FGalaxy_Events%3A_April_2011.md
git mv Special%3ABrowse/News-2FISMB_2013:_Automated_Function_Prediction.md Special%3ABrowse/News-2FISMB_2013%3A_Automated_Function_Prediction.md
git mv Special%3ABrowse/News-2FIntern_@_Aniseed:_work_on_Chado.md Special%3ABrowse/News-2FIntern_@_Aniseed%3A_work_on_Chado.md
git mv Special%3ABrowse/News-2FMAKER-2DP:_an_annotation_pipeline_for_plants.md Special%3ABrowse/News-2FMAKER-2DP%3A_an_annotation_pipeline_for_plants.md
git mv Special%3ABrowse/News-2FMaizeGDB:_Choosing_GBrowse.md Special%3ABrowse/News-2FMaizeGDB%3A_Choosing_GBrowse.md
git mv Special%3ABrowse/News-2FPathway_Tools_2010:_Virtual,_Now.md Special%3ABrowse/News-2FPathway_Tools_2010%3A_Virtual,_Now.md
git mv Special%3ABrowse/News-2FServer_Maintenance:_Sept_9.md Special%3ABrowse/News-2FServer_Maintenance%3A_Sept_9.md
git mv Special%3ABrowse/News-2FTripal:_A_Web_Front_End_for_Chado.md Special%3ABrowse/News-2FTripal%3A_A_Web_Front_End_for_Chado.md
git mv Special%3ABrowse/News-2FWebsite_Down:_Aug_11_2008.md Special%3ABrowse/News-2FWebsite_Down%3A_Aug_11_2008.md
git mv Special%3ABrowse/News-2FYAPC::NA_2010_is_Almost_Here!.md Special%3ABrowse/News-2FYAPC%3A%3ANA_2010_is_Almost_Here!.md
git mv Special%3ABrowse/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2F.md Special%3ABrowse/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2F.md
git mv Special%3ABrowse/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2FECOLI-2F.md Special%3ABrowse/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2FECOLI-2F.md
git mv Special%3ABrowse/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2Fdownload.shtml.md Special%3ABrowse/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2Fdownload.shtml.md
git mv Special%3ABrowse/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2Fotherpgdbs.shtml.md Special%3ABrowse/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2Fotherpgdbs.shtml.md
git mv Special%3ABrowse/Pathway-20Tools-23http:-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md Special%3ABrowse/Pathway-20Tools-23http%3A-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md
git mv Special%3ABrowse/Property:Allows_value.md Special%3ABrowse/Property%3AAllows_value.md
git mv Special%3ABrowse/Property:Available-20on-20platform.md Special%3ABrowse/Property%3AAvailable-20on-20platform.md
git mv Special%3ABrowse/Property:Available_on_platform.md Special%3ABrowse/Property%3AAvailable_on_platform.md
git mv Special%3ABrowse/Property:Has-20URL.md Special%3ABrowse/Property%3AHas-20URL.md
git mv Special%3ABrowse/Property:Has-20description.md Special%3ABrowse/Property%3AHas-20description.md
git mv Special%3ABrowse/Property:Has-20development-20status.md Special%3ABrowse/Property%3AHas-20development-20status.md
git mv Special%3ABrowse/Property:Has-20download-20URL.md Special%3ABrowse/Property%3AHas-20download-20URL.md
git mv Special%3ABrowse/Property:Has-20input-20format.md Special%3ABrowse/Property%3AHas-20input-20format.md
git mv Special%3ABrowse/Property:Has-20licence.md Special%3ABrowse/Property%3AHas-20licence.md
git mv Special%3ABrowse/Property:Has-20logo.md Special%3ABrowse/Property%3AHas-20logo.md
git mv Special%3ABrowse/Property:Has-20output-20format.md Special%3ABrowse/Property%3AHas-20output-20format.md
git mv Special%3ABrowse/Property:Has-20software-20maturity-20status.md Special%3ABrowse/Property%3AHas-20software-20maturity-20status.md
git mv Special%3ABrowse/Property:Has-20software-20prerequisite.md Special%3ABrowse/Property%3AHas-20software-20prerequisite.md
git mv Special%3ABrowse/Property:Has-20support-20status.md Special%3ABrowse/Property%3AHas-20support-20status.md
git mv Special%3ABrowse/Property:Has-20title.md Special%3ABrowse/Property%3AHas-20title.md
git mv Special%3ABrowse/Property:Has-20topic.md Special%3ABrowse/Property%3AHas-20topic.md
git mv Special%3ABrowse/Property:Has-20website.md Special%3ABrowse/Property%3AHas-20website.md
git mv Special%3ABrowse/Property:Has_URL.md Special%3ABrowse/Property%3AHas_URL.md
git mv Special%3ABrowse/Property:Has_default_form.md Special%3ABrowse/Property%3AHas_default_form.md
git mv Special%3ABrowse/Property:Has_description.md Special%3ABrowse/Property%3AHas_description.md
git mv Special%3ABrowse/Property:Has_development_status.md Special%3ABrowse/Property%3AHas_development_status.md
git mv Special%3ABrowse/Property:Has_download_URL.md Special%3ABrowse/Property%3AHas_download_URL.md
git mv Special%3ABrowse/Property:Has_input_format.md Special%3ABrowse/Property%3AHas_input_format.md
git mv Special%3ABrowse/Property:Has_licence.md Special%3ABrowse/Property%3AHas_licence.md
git mv Special%3ABrowse/Property:Has_logo.md Special%3ABrowse/Property%3AHas_logo.md
git mv Special%3ABrowse/Property:Has_output_format.md Special%3ABrowse/Property%3AHas_output_format.md
git mv Special%3ABrowse/Property:Has_software_maturity_status.md Special%3ABrowse/Property%3AHas_software_maturity_status.md
git mv Special%3ABrowse/Property:Has_software_prerequisite.md Special%3ABrowse/Property%3AHas_software_prerequisite.md
git mv Special%3ABrowse/Property:Has_subobject.md Special%3ABrowse/Property%3AHas_subobject.md
git mv Special%3ABrowse/Property:Has_support_status.md Special%3ABrowse/Property%3AHas_support_status.md
git mv Special%3ABrowse/Property:Has_title.md Special%3ABrowse/Property%3AHas_title.md
git mv Special%3ABrowse/Property:Has_topic.md Special%3ABrowse/Property%3AHas_topic.md
git mv Special%3ABrowse/Property:Has_type.md Special%3ABrowse/Property%3AHas_type.md
git mv Special%3ABrowse/Property:Has_website.md Special%3ABrowse/Property%3AHas_website.md
git mv Special%3ABrowse/Property:Interaction-20type.md Special%3ABrowse/Property%3AInteraction-20type.md
git mv Special%3ABrowse/Property:Interaction_type.md Special%3ABrowse/Property%3AInteraction_type.md
git mv Special%3ABrowse/Property:Interacts-20with.md Special%3ABrowse/Property%3AInteracts-20with.md
git mv Special%3ABrowse/Property:Interacts_with.md Special%3ABrowse/Property%3AInteracts_with.md
git mv Special%3ABrowse/Property:Is-20open-20source.md Special%3ABrowse/Property%3AIs-20open-20source.md
git mv Special%3ABrowse/Property:Is_open_source.md Special%3ABrowse/Property%3AIs_open_source.md
git mv Special%3ABrowse/Property:Link-20type.md Special%3ABrowse/Property%3ALink-20type.md
git mv Special%3ABrowse/Property:Link_type.md Special%3ABrowse/Property%3ALink_type.md
git mv Special%3ABrowse/Property:Linktitle.md Special%3ABrowse/Property%3ALinktitle.md
git mv Special%3ABrowse/Property:Linktype.md Special%3ABrowse/Property%3ALinktype.md
git mv Special%3ABrowse/Property:Release-20date.md Special%3ABrowse/Property%3ARelease-20date.md
git mv Special%3ABrowse/Property:Release_date.md Special%3ABrowse/Property%3ARelease_date.md
git mv Special%3ABrowse/Property:Subject.md Special%3ABrowse/Property%3ASubject.md
git mv Special%3ABrowse/Property:Tool-20functionality-20or-20classification.md Special%3ABrowse/Property%3ATool-20functionality-20or-20classification.md
git mv Special%3ABrowse/Property:Tool_functionality_or_classification.md Special%3ABrowse/Property%3ATool_functionality_or_classification.md
git mv Special%3ABrowse/Property:Written-20in-20language.md Special%3ABrowse/Property%3AWritten-20in-20language.md
git mv Special%3ABrowse/Property:Written_in_language.md Special%3ABrowse/Property%3AWritten_in_language.md
git mv Special%3ABrowse/Textpresso-23http:-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide.md Special%3ABrowse/Textpresso-23http%3A-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide.md
git mv Special%3ABrowse/Textpresso-23http:-2F-2Ftextpresso.org-2Fdownloads.html.md Special%3ABrowse/Textpresso-23http%3A-2F-2Ftextpresso.org-2Fdownloads.html.md
git mv Special%3ABrowse/Textpresso-23http:-2F-2Ftextpresso.org.md Special%3ABrowse/Textpresso-23http%3A-2F-2Ftextpresso.org.md
git mv Special%3ABrowse/Textpresso-23http:-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F.md Special%3ABrowse/Textpresso-23http%3A-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F.md
git mv Special%3ABrowse/Textpresso-23http:-2F-2Fwhis.caltech.edu-2Ftextpresso-2F.md Special%3ABrowse/Textpresso-23http%3A-2F-2Fwhis.caltech.edu-2Ftextpresso-2F.md
git mv Special%3ABrowse/Textpresso-23http:-2F-2Fwww.textpresso.org-2Fcelegans-2F.md Special%3ABrowse/Textpresso-23http%3A-2F-2Fwww.textpresso.org-2Fcelegans-2F.md
git mv Special%3ABrowse/Tripal-23http:-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation.md Special%3ABrowse/Tripal-23http%3A-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation.md
git mv Special%3ABrowse/Tripal-23http:-2F-2Ftripal.info.md Special%3ABrowse/Tripal-23http%3A-2F-2Ftripal.info.md
git mv Special%3ABrowse/User:Alexkalderimis.md Special%3ABrowse/User%3AAlexkalderimis.md
git mv Special%3ABrowse/User:Alpapan.md Special%3ABrowse/User%3AAlpapan.md
git mv Special%3ABrowse/User:Baranda.md Special%3ABrowse/User%3ABaranda.md
git mv Special%3ABrowse/User:Bilardi.md Special%3ABrowse/User%3ABilardi.md
git mv Special%3ABrowse/User:Bmoore.md Special%3ABrowse/User%3ABmoore.md
git mv Special%3ABrowse/User:Bosborne.md Special%3ABrowse/User%3ABosborne.md
git mv Special%3ABrowse/User:Brianfoley.md Special%3ABrowse/User%3ABrianfoley.md
git mv Special%3ABrowse/User:Buggy.md Special%3ABrowse/User%3ABuggy.md
git mv Special%3ABrowse/User:Carsonholt.md Special%3ABrowse/User%3ACarsonholt.md
git mv Special%3ABrowse/User:Chemmeri.md Special%3ABrowse/User%3AChemmeri.md
git mv Special%3ABrowse/User:Childers.md Special%3ABrowse/User%3AChilders.md
git mv Special%3ABrowse/User:Chinmay.md Special%3ABrowse/User%3AChinmay.md
git mv Special%3ABrowse/User:Cjfields.md Special%3ABrowse/User%3ACjfields.md
git mv Special%3ABrowse/User:Clements.md Special%3ABrowse/User%3AClements.md
git mv Special%3ABrowse/User:Colin_Diesh.md Special%3ABrowse/User%3AColin_Diesh.md
git mv Special%3ABrowse/User:Dan.md Special%3ABrowse/User%3ADan.md
git mv Special%3ABrowse/User:DanB.md Special%3ABrowse/User%3ADanB.md
git mv Special%3ABrowse/User:DanBolser.md Special%3ABrowse/User%3ADanBolser.md
git mv Special%3ABrowse/User:DanielRenfro.md Special%3ABrowse/User%3ADanielRenfro.md
git mv Special%3ABrowse/User:Dongilbert.md Special%3ABrowse/User%3ADongilbert.md
git mv Special%3ABrowse/User:Dukeleto.md Special%3ABrowse/User%3ADukeleto.md
git mv Special%3ABrowse/User:Elee.md Special%3ABrowse/User%3AElee.md
git mv Special%3ABrowse/User:Eric.ganko.md Special%3ABrowse/User%3AEric.ganko.md
git mv Special%3ABrowse/User:Eric_Rasche.md Special%3ABrowse/User%3AEric_Rasche.md
git mv Special%3ABrowse/User:ErickAntezana.md Special%3ABrowse/User%3AErickAntezana.md
git mv Special%3ABrowse/User:Faga.md Special%3ABrowse/User%3AFaga.md
git mv Special%3ABrowse/User:Garrett.md Special%3ABrowse/User%3AGarrett.md
git mv Special%3ABrowse/User:Girlwithglasses-2FTemplate:StandardToolDisplay.md Special%3ABrowse/User%3AGirlwithglasses-2FTemplate%3AStandardToolDisplay.md
git mv Special%3ABrowse/User:Girlwithglasses-2FTemplate:ToolData-2Fgbrowse.md Special%3ABrowse/User%3AGirlwithglasses-2FTemplate%3AToolData-2Fgbrowse.md
git mv Special%3ABrowse/User:Girlwithglasses-2FTemplate:ToolData-2Fgbrowse_syn.md Special%3ABrowse/User%3AGirlwithglasses-2FTemplate%3AToolData-2Fgbrowse_syn.md
git mv Special%3ABrowse/User:Girlwithglasses-2FTemplate:ToolData-2Fgeneric.md Special%3ABrowse/User%3AGirlwithglasses-2FTemplate%3AToolData-2Fgeneric.md
git mv Special%3ABrowse/User:Girlwithglasses.md Special%3ABrowse/User%3AGirlwithglasses.md
git mv Special%3ABrowse/User:GreggHelt2.md Special%3ABrowse/User%3AGreggHelt2.md
git mv Special%3ABrowse/User:Hlapp.md Special%3ABrowse/User%3AHlapp.md
git mv Special%3ABrowse/User:JWarren.md Special%3ABrowse/User%3AJWarren.md
git mv Special%3ABrowse/User:JamesTaylor.md Special%3ABrowse/User%3AJamesTaylor.md
git mv Special%3ABrowse/User:Jhannah.md Special%3ABrowse/User%3AJhannah.md
git mv Special%3ABrowse/User:JimHu-2FGbrowse.md Special%3ABrowse/User%3AJimHu-2FGbrowse.md
git mv Special%3ABrowse/User:JimHu.md Special%3ABrowse/User%3AJimHu.md
git mv Special%3ABrowse/User:Jogoodma.md Special%3ABrowse/User%3AJogoodma.md
git mv Special%3ABrowse/User:Jorvis.md Special%3ABrowse/User%3AJorvis.md
git mv Special%3ABrowse/User:JunZhao.md Special%3ABrowse/User%3AJunZhao.md
git mv Special%3ABrowse/User:Junjun.md Special%3ABrowse/User%3AJunjun.md
git mv Special%3ABrowse/User:Justaddcoffee.md Special%3ABrowse/User%3AJustaddcoffee.md
git mv Special%3ABrowse/User:Lstein.md Special%3ABrowse/User%3ALstein.md
git mv Special%3ABrowse/User:Mara_Kim.md Special%3ABrowse/User%3AMara_Kim.md
git mv Special%3ABrowse/User:Mcaudy.md Special%3ABrowse/User%3AMcaudy.md
git mv Special%3ABrowse/User:Mckays.md Special%3ABrowse/User%3AMckays.md
git mv Special%3ABrowse/User:Mestato.md Special%3ABrowse/User%3AMestato.md
git mv Special%3ABrowse/User:Michael_Campbell.md Special%3ABrowse/User%3AMichael_Campbell.md
git mv Special%3ABrowse/User:MitchSkinner.md Special%3ABrowse/User%3AMitchSkinner.md
git mv Special%3ABrowse/User:Mnrusimh.md Special%3ABrowse/User%3AMnrusimh.md
git mv Special%3ABrowse/User:Moni.md Special%3ABrowse/User%3AMoni.md
git mv Special%3ABrowse/User:NLWashington.md Special%3ABrowse/User%3ANLWashington.md
git mv Special%3ABrowse/User:NaamaMenda.md Special%3ABrowse/User%3ANaamaMenda.md
git mv Special%3ABrowse/User:RBuels.md Special%3ABrowse/User%3ARBuels.md
git mv Special%3ABrowse/User:RSCummings.md Special%3ABrowse/User%3ARSCummings.md
git mv Special%3ABrowse/User:Richard_Hayes.md Special%3ABrowse/User%3ARichard_Hayes.md
git mv Special%3ABrowse/User:RobertBuels.md Special%3ABrowse/User%3ARobertBuels.md
git mv Special%3ABrowse/User:Robin.haw.md Special%3ABrowse/User%3ARobin.haw.md
git mv Special%3ABrowse/User:RobinHouston.md Special%3ABrowse/User%3ARobinHouston.md
git mv Special%3ABrowse/User:Rsmith.md Special%3ABrowse/User%3ARsmith.md
git mv Special%3ABrowse/User:Russellsmithies.md Special%3ABrowse/User%3ARussellsmithies.md
git mv Special%3ABrowse/User:Scott.md Special%3ABrowse/User%3AScott.md
git mv Special%3ABrowse/User:Sficklin.md Special%3ABrowse/User%3ASficklin.md
git mv Special%3ABrowse/User:Sivam.md Special%3ABrowse/User%3ASivam.md
git mv Special%3ABrowse/User:Sperling.md Special%3ABrowse/User%3ASperling.md
git mv Special%3ABrowse/User:Stajich.md Special%3ABrowse/User%3AStajich.md
git mv Special%3ABrowse/User:Stevef.md Special%3ABrowse/User%3AStevef.md
git mv Special%3ABrowse/User:Stewarta.md Special%3ABrowse/User%3AStewarta.md
git mv Special%3ABrowse/User:Sundaram.md Special%3ABrowse/User%3ASundaram.md
git mv Special%3ABrowse/User:SyedHaider.md Special%3ABrowse/User%3ASyedHaider.md
git mv Special%3ABrowse/User:Tharris.md Special%3ABrowse/User%3ATharris.md
git mv Special%3ABrowse/User:TimCarver.md Special%3ABrowse/User%3ATimCarver.md
git mv Special%3ABrowse/User:Tjvision.md Special%3ABrowse/User%3ATjvision.md
git mv Special%3ABrowse/User:Xshi.md Special%3ABrowse/User%3AXshi.md
git mv Special%3ABrowse/User:Ybendana.md Special%3ABrowse/User%3AYbendana.md
git mv Special%3ABrowse/WebApollo-23http:-2F-2Fcode.google.com-2Fp-2Fgenomancer.md Special%3ABrowse/WebApollo-23http%3A-2F-2Fcode.google.com-2Fp-2Fgenomancer.md
git mv Special%3ABrowse/WebApollo-23http:-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F.md Special%3ABrowse/WebApollo-23http%3A-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F.md
git mv Special%3ABrowse/WebApollo-23http:-2F-2Fgenomearchitect.org.md Special%3ABrowse/WebApollo-23http%3A-2F-2Fgenomearchitect.org.md
git mv Special%3ABrowse/WebApollo-23http:-2F-2Fgenomearchitect.org:8080-2FWebApolloDemo-2F.md Special%3ABrowse/WebApollo-23http%3A-2F-2Fgenomearchitect.org%3A8080-2FWebApolloDemo-2F.md
git mv Special%3ABrowse/WebApollo-23https:-2F-2Fgithub.com-2Fgmod-2Fapollo.md Special%3ABrowse/WebApollo-23https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo.md
git mv Special%3ABrowse/WebApollo2-23http:-2F-2Fgenomearchitect.org.md Special%3ABrowse/WebApollo2-23http%3A-2F-2Fgenomearchitect.org.md
git mv Special%3ABrowse/WebApollo2-23http:-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex.md Special%3ABrowse/WebApollo2-23http%3A-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex.md
git mv Special%3ABrowse/WebApollo2-23https:-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases.md Special%3ABrowse/WebApollo2-23https%3A-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases.md
git mv Special%3ABrowse/WebApollo2-23https:-2F-2Fgithub.com-2Fgmod-2Fapollo.md Special%3ABrowse/WebApollo2-23https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo.md
git mv Special%3ABrowse/WebGBrowse-23http:-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md Special%3ABrowse/WebGBrowse-23http%3A-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md
git mv Special%3ABrowse/WebGBrowse-23http:-2F-2Fwebgbrowse.cgb.indiana.edu.md Special%3ABrowse/WebGBrowse-23http%3A-2F-2Fwebgbrowse.cgb.indiana.edu.md
git mv Special%3ABrowse/XORT-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md Special%3ABrowse/XORT-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md
