git mv Special%3ABrowse/CMap-23http:-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM\;ref_map_aids=109.md Special%3ABrowse/CMap-23http%3A-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM\;ref_map_aids=109.md
git mv Special%3ABrowse/GBrowse-20syn-23http:-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele\;name=X:1050001..1150000.md Special%3ABrowse/GBrowse-20syn-23http%3A-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele\;name=X%3A1050001..1150000.md
git mv Special%3ABrowse/GBrowse-20syn-23http:-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri\;name=chrX:620000..670000.md Special%3ABrowse/GBrowse-20syn-23http%3A-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri\;name=chrX%3A620000..670000.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbeetlebase.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbeetlebase.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbiocyc.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbiocyc.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbiocyc.org-2FECOLI-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbiocyc.org-2FECOLI-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbiocyc.org-2Fdownload.shtml.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbiocyc.org-2Fdownload.shtml.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbiocyc.org-2Fotherpgdbs.shtml.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbiocyc.org-2Fotherpgdbs.shtml.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbioinf.scri.sari.ac.uk-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbioinf.scri.sari.ac.uk-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fcode.google.com-2Fp-2Fgenomancer.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fcode.google.com-2Fp-2Fgenomancer.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fcuration.pombase.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fcuration.pombase.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fcuration.pombase.org-2Fdemo.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fcuration.pombase.org-2Fdemo.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fcuration.pombase.org-2Fpombe.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fcuration.pombase.org-2Fpombe.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fcuration.pombase.org-2Funiprot.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fcuration.pombase.org-2Funiprot.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele-253Bname=X:1050001..1150000.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele-253Bname=X%3A1050001..1150000.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgbrowse.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgbrowse.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgenomearchitect.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgenomearchitect.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgenomearchitect.org:8080-2FWebApolloDemo-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgenomearchitect.org%3A8080-2FWebApolloDemo-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgenomesunzipped.org-2Fjbrowse.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgenomesunzipped.org-2Fjbrowse.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgetgalaxy.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgetgalaxy.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgithub.com-2FGMOD-2Fjbrowse.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fhymenopteragenome.org-2Fant_genomes-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fhymenopteragenome.org-2Fant_genomes-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ficemangenome.net-2F-25E2-2580-258E.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ficemangenome.net-2F-25E2-2580-258E.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fjbrowse.org-2Fdemos.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fjbrowse.org-2Fdemos.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fjbrowse.org-2Finstall-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fjbrowse.org-2Finstall-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fjbrowse.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fjbrowse.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fmap.lab.nig.ac.jp:8080-2Fcmap-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fmap.lab.nig.ac.jp%3A8080-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri-253Bname=chrX:620000..670000.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri-253Bname=chrX%3A620000..670000.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fmedvet.angis.org.au-2Fcmap-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fmedvet.angis.org.au-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fratmine.mcw.edu-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fratmine.mcw.edu-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Frye.pw.usda.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info-3Fmap_set_aid=Barley_consensus_2003.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Frye.pw.usda.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info-3Fmap_set_aid=Barley_consensus_2003.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fsoybeanbreederstoolbox.org-2Findex.php.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fsoybeanbreederstoolbox.org-2Findex.php.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftextpresso.org-2Fdownloads.html.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftextpresso.org-2Fdownloads.html.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftextpresso.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftextpresso.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftripal.info.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftripal.info.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftropgenedb.cirad.fr.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftropgenedb.cirad.fr.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Ftwitter.com-2Fusejbrowse.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Ftwitter.com-2Fusejbrowse.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwebgbrowse.cgb.indiana.edu.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwebgbrowse.cgb.indiana.edu.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwhis.caltech.edu-2Ftextpresso-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwhis.caltech.edu-2Ftextpresso-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.bioinfo.wsu.edu-2Fcgi-2Dbin-2Fgdr-2Fcmap-2Fmap_set_info-3Fmap_set_aid=17.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.bioinfo.wsu.edu-2Fcgi-2Dbin-2Fgdr-2Fcmap-2Fmap_set_info-3Fmap_set_aid=17.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.biomart.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.biomart.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.biomart.org-2Fcommunity.html.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.biomart.org-2Fcommunity.html.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.biomart.org-2Fdownload.html.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.biomart.org-2Fdownload.html.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.comparative-2Dlegumes.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.comparative-2Dlegumes.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.cottondb.org-2Fcmap-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.cottondb.org-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.cottonmarker.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.cottonmarker.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.flymine.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.flymine.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.gramene.org-2Fcmap.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.gramene.org-2Fcmap.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.gramene.org-2Fdb-2Fcmap.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.gramene.org-2Fdb-2Fcmap.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.intermine.org.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.intermine.org.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.mousemine.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.mousemine.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM-253Bref_map_aids=109.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.pristionchus.org-2Fcgi-2Dbin-2Fcmap-2Fviewer-3Fref_map_set_aid=PM-253Bref_map_aids=109.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.textpresso.org-2Fcelegans-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.textpresso.org-2Fcelegans-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fyeastmine.yeastgenome.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fyeastmine.yeastgenome.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/http:-2F-2Fzmine.zfin.org-2F.md Special%3ASearchByProperty/Has-20URL/http%3A-2F-2Fzmine.zfin.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fdocs.galaxyproject.org.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fdocs.galaxyproject.org.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgalaxyproject.github.io.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgalaxyproject.github.io.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgalaxyproject.org-2F.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgalaxyproject.org-2F.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgalaxyproject.org-2Fuse-2F.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgalaxyproject.org-2Fuse-2F.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2FGMOD-2FGBrowse.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2Fbioteam-2FDIYA.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2Fbioteam-2FDIYA.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2Fgmod-2Fapollo.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2Fintermine-2Fintermine.git.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2Fintermine-2Fintermine.git.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgithub.com-2Fpombase-2Fcanto.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Ftwitter.com-2Fgalaxyproject.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Ftwitter.com-2Fgalaxyproject.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48.md
git mv Special%3ASearchByProperty/Has-20URL/https:-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy.md Special%3ASearchByProperty/Has-20URL/https%3A-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy.md
git mv Special%3ASearchByProperty/Has-20description/Username:-20demo@demo.com,-20Password:-20demo.md Special%3ASearchByProperty/Has-20description/Username%3A-20demo@demo.com,-20Password%3A-20demo.md
git mv Special%3ASearchByProperty/Has-20download-20URL/http:-2F-2Fbiocyc.org-2Fdownload.shtml.md Special%3ASearchByProperty/Has-20download-20URL/http%3A-2F-2Fbiocyc.org-2Fdownload.shtml.md
git mv Special%3ASearchByProperty/Has-20download-20URL/http:-2F-2Fgithub.com-2Fidoerg-2FBioDIG.md Special%3ASearchByProperty/Has-20download-20URL/http%3A-2F-2Fgithub.com-2Fidoerg-2FBioDIG.md
git mv Special%3ASearchByProperty/Has-20download-20URL/http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md Special%3ASearchByProperty/Has-20download-20URL/http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md
git mv Special%3ASearchByProperty/Has-20download-20URL/http:-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md Special%3ASearchByProperty/Has-20download-20URL/http%3A-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md
git mv Special%3ASearchByProperty/Has-20download-20URL/https:-2F-2Fgithub.com-2FGMOD-2FGBrowse.md Special%3ASearchByProperty/Has-20download-20URL/https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttp:-2F-2Fopensource.org-2Flicenses-2FAFL-2D3.0-20Academic-20Free-20License-203.0-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttp%3A-2F-2Fopensource.org-2Flicenses-2FAFL-2D3.0-20Academic-20Free-20License-203.0-5D.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttp:-2F-2Fopensource.org-2Flicenses-2FArtistic-2D2.0-20Artistic-20License-202.0-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttp%3A-2F-2Fopensource.org-2Flicenses-2FArtistic-2D2.0-20Artistic-20License-202.0-5D.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttp:-2F-2Fopensource.org-2Flicenses-2FGPL-2D3.0-20GPL-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttp%3A-2F-2Fopensource.org-2Flicenses-2FGPL-2D3.0-20GPL-5D.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttp:-2F-2Fopensource.org-2Flicenses-2FLGPL-2D3.0-20LGPL-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttp%3A-2F-2Fopensource.org-2Flicenses-2FLGPL-2D3.0-20LGPL-5D.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttp:-2F-2Fopensource.org-2Flicenses-2Fgpl-2Dlicense-20GNU-20GPL-20\(for-20academics\)-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttp%3A-2F-2Fopensource.org-2Flicenses-2Fgpl-2Dlicense-20GNU-20GPL-20\(for-20academics\)-5D.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttp:-2F-2Fopensource.org-2Flicenses-2Fgpl-2Dlicense-20Gnu-20GPL-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttp%3A-2F-2Fopensource.org-2Flicenses-2Fgpl-2Dlicense-20Gnu-20GPL-5D.md
git mv Special%3ASearchByProperty/Has-20licence/-5Bhttps:-2F-2Fopensource.org-2Flicenses-2FApache-2D2.0-20Apache-202-5D.md Special%3ASearchByProperty/Has-20licence/-5Bhttps%3A-2F-2Fopensource.org-2Flicenses-2FApache-2D2.0-20Apache-202-5D.md
git mv Special%3ASearchByProperty/Has-20output-20format/APIs:-20REST-2FSOAP.md Special%3ASearchByProperty/Has-20output-20format/APIs%3A-20REST-2FSOAP.md
git mv Special%3ASearchByProperty/Has-20publication-20details/BMC-20Genomics-2014:1-20741.md Special%3ASearchByProperty/Has-20publication-20details/BMC-20Genomics-2014%3A1-20741.md
git mv Special%3ASearchByProperty/Has-20publication-20details/Current-20protocols-20in-20bioinformatics-20-2F-20editoral-20board,-20Andreas-20D.-20Baxevanis-20...-20-5Bet-20al.-5D-20Chapter-209:-20Unit-209.12.md Special%3ASearchByProperty/Has-20publication-20details/Current-20protocols-20in-20bioinformatics-20-2F-20editoral-20board,-20Andreas-20D.-20Baxevanis-20...-20-5Bet-20al.-5D-20Chapter-209%3A-20Unit-209.12.md
git mv Special%3ASearchByProperty/Has-20publication-20details/Database-20:-20the-20journal-20of-20biological-20databases-20and-20curation-202011:-20bar044.md Special%3ASearchByProperty/Has-20publication-20details/Database-20%3A-20the-20journal-20of-20biological-20databases-20and-20curation-202011%3A-20bar044.md
git mv Special%3ASearchByProperty/Has-20publication-20details/Genome-20research-2012:-201599-2D610.md Special%3ASearchByProperty/Has-20publication-20details/Genome-20research-2012%3A-201599-2D610.md
git mv Special%3ASearchByProperty/Has-20subobject/BLAST-20Graphic-20Viewer-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F.md Special%3ASearchByProperty/Has-20subobject/BLAST-20Graphic-20Viewer-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FblastGraphic-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/BLAST-20Graphic-20Viewer-23http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl.md Special%3ASearchByProperty/Has-20subobject/BLAST-20Graphic-20Viewer-23http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2Fblast-2Dsgd.pl.md
git mv Special%3ASearchByProperty/Has-20subobject/BioMart-23http:-2F-2Fwww.biomart.org-2F.md Special%3ASearchByProperty/Has-20subobject/BioMart-23http%3A-2F-2Fwww.biomart.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/BioMart-23http:-2F-2Fwww.biomart.org-2Fcommunity.html.md Special%3ASearchByProperty/Has-20subobject/BioMart-23http%3A-2F-2Fwww.biomart.org-2Fcommunity.html.md
git mv Special%3ASearchByProperty/Has-20subobject/BioMart-23http:-2F-2Fwww.biomart.org-2Fdownload.html.md Special%3ASearchByProperty/Has-20subobject/BioMart-23http%3A-2F-2Fwww.biomart.org-2Fdownload.html.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fbioinf.scri.sari.ac.uk-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fbioinf.scri.sari.ac.uk-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fbioinformatics.pbcbasc.latrobe.edu.au-2Fbasc-2Fcgi-2Dbin-2Findex.cgi.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fcricket.ornl.gov-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fmagi.plantgenomics.iastate.edu-2Fcgi-2Dbin-2Fcmap-2Fmap_set_info.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fmap.lab.nig.ac.jp:8080-2Fcmap-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fmap.lab.nig.ac.jp%3A8080-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fmedvet.angis.org.au-2Fcmap-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fmedvet.angis.org.au-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fpeanutgenetics.tamu.edu-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fracerx00.tamu.edu-2Fcgi-2Dbin-2Fcmap-2Fviewer.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fsoybeanbreederstoolbox.org-2Findex.php.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fsoybeanbreederstoolbox.org-2Findex.php.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Ftropgenedb.cirad.fr.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Ftropgenedb.cirad.fr.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fwww.comparative-2Dlegumes.org-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fwww.comparative-2Dlegumes.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fwww.cottondb.org-2Fcmap-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fwww.cottondb.org-2Fcmap-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fwww.cottonmarker.org-2F.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fwww.cottonmarker.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fwww.gramene.org-2Fcmap.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fwww.gramene.org-2Fcmap.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23http:-2F-2Fwww.gramene.org-2Fdb-2Fcmap.md Special%3ASearchByProperty/Has-20subobject/CMap-23http%3A-2F-2Fwww.gramene.org-2Fdb-2Fcmap.md
git mv Special%3ASearchByProperty/Has-20subobject/CMap-23https:-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap.md Special%3ASearchByProperty/Has-20subobject/CMap-23https%3A-2F-2Fgmod.svn.sourceforge.net-2Fsvnroot-2Fgmod-2Fcmap.md
git mv Special%3ASearchByProperty/Has-20subobject/Canto-23http:-2F-2Fcuration.pombase.org-2F.md Special%3ASearchByProperty/Has-20subobject/Canto-23http%3A-2F-2Fcuration.pombase.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Canto-23http:-2F-2Fcuration.pombase.org-2Fdemo.md Special%3ASearchByProperty/Has-20subobject/Canto-23http%3A-2F-2Fcuration.pombase.org-2Fdemo.md
git mv Special%3ASearchByProperty/Has-20subobject/Canto-23http:-2F-2Fcuration.pombase.org-2Fpombe.md Special%3ASearchByProperty/Has-20subobject/Canto-23http%3A-2F-2Fcuration.pombase.org-2Fpombe.md
git mv Special%3ASearchByProperty/Has-20subobject/Canto-23http:-2F-2Fcuration.pombase.org-2Funiprot.md Special%3ASearchByProperty/Has-20subobject/Canto-23http%3A-2F-2Fcuration.pombase.org-2Funiprot.md
git mv Special%3ASearchByProperty/Has-20subobject/Canto-23https:-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin.md Special%3ASearchByProperty/Has-20subobject/Canto-23https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto-2Fblob-2Fmaster-2Fdocumentation-2Fcanto_admin.md
git mv Special%3ASearchByProperty/Has-20subobject/Canto-23https:-2F-2Fgithub.com-2Fpombase-2Fcanto.md Special%3ASearchByProperty/Has-20subobject/Canto-23https%3A-2F-2Fgithub.com-2Fpombase-2Fcanto.md
git mv Special%3ASearchByProperty/Has-20subobject/DIYA-23https:-2F-2Fgithub.com-2Fbioteam-2FDIYA.md Special%3ASearchByProperty/Has-20subobject/DIYA-23https%3A-2F-2Fgithub.com-2Fbioteam-2FDIYA.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http:-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele\;name=X:1050001..1150000.md Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http%3A-2F-2Fdev.wormbase.org-2Fdb-2Fseq-2Fgbrowse_syn-2Fcompara-3Fsearch_src=Cele\;name=X%3A1050001..1150000.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http:-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri\;name=chrX:620000..670000.md Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http%3A-2F-2Fmckay.cshl.edu-2Fcgi-2Dbin-2Fgbrowse_syn-2Fmercator-2F-3Fsearch_src=Cbri\;name=chrX%3A620000..670000.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http:-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F.md Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http%3A-2F-2Fsolgenomics.net-2Fgbrowse2-2Fbin-2Fgbrowse_syn-2Fsol3-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http:-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501.md Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23http%3A-2F-2Fwww.arabidopsis.org-2Fcgi-2Dbin-2Fgbrowse_syn-2Farabidopsis-2F-3Fname=Chr1-253A8367000..8370501.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23https:-2F-2Fgithub.com-2FGMOD-2FGBrowse.md Special%3ASearchByProperty/Has-20subobject/GBrowse-20syn-23https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-23http:-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel.md Special%3ASearchByProperty/Has-20subobject/GBrowse-23http%3A-2F-2Fflybase.org-2Fcgi-2Dbin-2Fgbrowse-2Fdmel.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-23http:-2F-2Fgbrowse.org.md Special%3ASearchByProperty/Has-20subobject/GBrowse-23http%3A-2F-2Fgbrowse.org.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-23http:-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse.md Special%3ASearchByProperty/Has-20subobject/GBrowse-23http%3A-2F-2Fhapmap.ncbi.nlm.nih.gov-2Fcgi-2Dperl-2Fgbrowse-2Fgbrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F.md Special%3ASearchByProperty/Has-20subobject/GBrowse-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGeneric-2520Genome-2520Browser-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-23http:-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F.md Special%3ASearchByProperty/Has-20subobject/GBrowse-23http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fgenome-2Fgbrowse-2Fc_elegans-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/GBrowse-23https:-2F-2Fgithub.com-2FGMOD-2FGBrowse.md Special%3ASearchByProperty/Has-20subobject/GBrowse-23https%3A-2F-2Fgithub.com-2FGMOD-2FGBrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/GO-20Graphic-20Viewer-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F.md Special%3ASearchByProperty/Has-20subobject/GO-20Graphic-20Viewer-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FGOView-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/GO-20Graphic-20Viewer-23http:-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl.md Special%3ASearchByProperty/Has-20subobject/GO-20Graphic-20Viewer-23http%3A-2F-2Fwww.yeastgenome.org-2Fcgi-2Dbin-2FGO-2FgoTermFinder.pl.md
git mv Special%3ASearchByProperty/Has-20subobject/GO::TermFinder-23http:-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder.md Special%3ASearchByProperty/Has-20subobject/GO%3A%3ATermFinder-23http%3A-2F-2Fgo.princeton.edu-2Fcgi-2Dbin-2FGOTermFinder-2FGOTermFinder.md
git mv Special%3ASearchByProperty/Has-20subobject/GO::TermFinder-23http:-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F.md Special%3ASearchByProperty/Has-20subobject/GO%3A%3ATermFinder-23http%3A-2F-2Fsearch.cpan.org-2Fdist-2FGO-2DTermFinder-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23http:-2F-2Fgetgalaxy.org-2F.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23http%3A-2F-2Fgetgalaxy.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23http:-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23http%3A-2F-2Fwiki.galaxyproject.org-2FPublicGalaxyServers.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Fdocs.galaxyproject.org.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Fdocs.galaxyproject.org.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Fgalaxyproject.github.io.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Fgalaxyproject.github.io.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Fgalaxyproject.org-2F.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Fgalaxyproject.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Fgalaxyproject.org-2Fuse-2F.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Fgalaxyproject.org-2Fuse-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Fgithub.com-2Fgalaxyproject-2Fgalaxy-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Ftwitter.com-2Fgalaxyproject.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Ftwitter.com-2Fgalaxyproject.md
git mv Special%3ASearchByProperty/Has-20subobject/Galaxy-23https:-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy.md Special%3ASearchByProperty/Has-20subobject/Galaxy-23https%3A-2F-2Fwww.zotero.org-2Fgroups-2F1732893-2Fgalaxy.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fratmine.mcw.edu-2F.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fratmine.mcw.edu-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fwww.flymine.org.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fwww.flymine.org.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fwww.intermine.org.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fwww.intermine.org.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fwww.mousemine.org-2F.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fwww.mousemine.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fwww.wormbase.org-2Ftools-2Fwormmine.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fyeastmine.yeastgenome.org-2F.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fyeastmine.yeastgenome.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23http:-2F-2Fzmine.zfin.org-2F.md Special%3ASearchByProperty/Has-20subobject/InterMine-23http%3A-2F-2Fzmine.zfin.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/InterMine-23https:-2F-2Fgithub.com-2Fintermine-2Fintermine.git.md Special%3ASearchByProperty/Has-20subobject/InterMine-23https%3A-2F-2Fgithub.com-2Fintermine-2Fintermine.git.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fbeetlebase.org.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fbeetlebase.org.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fgenomesunzipped.org-2Fjbrowse.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fgenomesunzipped.org-2Fjbrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fgithub.com-2FGMOD-2Fjbrowse.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Ficemangenome.net-2F.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Ficemangenome.net-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fjbrowse.org-2Fdemos.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fjbrowse.org-2Fdemos.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fjbrowse.org-2Finstall-2F.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fjbrowse.org-2Finstall-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fjbrowse.org.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fjbrowse.org.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Ftwitter.com-2Fusejbrowse.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Ftwitter.com-2Fusejbrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse-23http:-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F.md Special%3ASearchByProperty/Has-20subobject/JBrowse-23http%3A-2F-2Fwww.medicinalgenomics.com-2Fthe-2Djane-2Dome-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse2-23http:-2F-2Fjbrowse.org-2Fdemos.md Special%3ASearchByProperty/Has-20subobject/JBrowse2-23http%3A-2F-2Fjbrowse.org-2Fdemos.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse2-23http:-2F-2Fjbrowse.org.md Special%3ASearchByProperty/Has-20subobject/JBrowse2-23http%3A-2F-2Fjbrowse.org.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse2-23http:-2F-2Ftwitter.com-2Fusejbrowse.md Special%3ASearchByProperty/Has-20subobject/JBrowse2-23http%3A-2F-2Ftwitter.com-2Fusejbrowse.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse2-23https:-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F.md Special%3ASearchByProperty/Has-20subobject/JBrowse2-23https%3A-2F-2Fgithub.com-2FGMOD-2Fjbrowse-2Dcomponents-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/JBrowse2-23https:-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web.md Special%3ASearchByProperty/Has-20subobject/JBrowse2-23https%3A-2F-2Fjbrowse.org-2Fjb2-2Fdocs-2Fquickstart_web.md
git mv Special%3ASearchByProperty/Has-20subobject/MAKER-23http:-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi.md Special%3ASearchByProperty/Has-20subobject/MAKER-23http%3A-2F-2Fderringer.genetics.utah.edu-2Fcgi-2Dbin-2FMWAS-2Fmaker.cgi.md
git mv Special%3ASearchByProperty/Has-20subobject/MAKER-23http:-2F-2Fhymenopteragenome.org-2Fant_genomes-2F.md Special%3ASearchByProperty/Has-20subobject/MAKER-23http%3A-2F-2Fhymenopteragenome.org-2Fant_genomes-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/MAKER-23http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html.md Special%3ASearchByProperty/Has-20subobject/MAKER-23http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker-2Dp.html.md
git mv Special%3ASearchByProperty/Has-20subobject/MAKER-23http:-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html.md Special%3ASearchByProperty/Has-20subobject/MAKER-23http%3A-2F-2Fwww.yandell-2Dlab.org-2Fsoftware-2Fmaker.html.md
git mv Special%3ASearchByProperty/Has-20subobject/MAKER-23http:-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi.md Special%3ASearchByProperty/Has-20subobject/MAKER-23http%3A-2F-2Fyandell.topaz.genetics.utah.edu-2Fcgi-2Dbin-2Fmaker_license.cgi.md
git mv Special%3ASearchByProperty/Has-20subobject/MAKER-23https:-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48.md Special%3ASearchByProperty/Has-20subobject/MAKER-23https%3A-2F-2Fwww.e-2Dbiogenouest.org-2Fresources-2F48.md
git mv Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2F.md Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2FECOLI-2F.md Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2FECOLI-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2Fdownload.shtml.md Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2Fdownload.shtml.md
git mv Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http:-2F-2Fbiocyc.org-2Fotherpgdbs.shtml.md Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http%3A-2F-2Fbiocyc.org-2Fotherpgdbs.shtml.md
git mv Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http:-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md Special%3ASearchByProperty/Has-20subobject/Pathway-20Tools-23http%3A-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Textpresso-23http:-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide.md Special%3ASearchByProperty/Has-20subobject/Textpresso-23http%3A-2F-2Ftextpresso-2Dwww.caltech.edu-2Fcgi-2Dbin-2Fcelegans-2Fuser_guide.md
git mv Special%3ASearchByProperty/Has-20subobject/Textpresso-23http:-2F-2Ftextpresso.org-2Fdownloads.html.md Special%3ASearchByProperty/Has-20subobject/Textpresso-23http%3A-2F-2Ftextpresso.org-2Fdownloads.html.md
git mv Special%3ASearchByProperty/Has-20subobject/Textpresso-23http:-2F-2Ftextpresso.org.md Special%3ASearchByProperty/Has-20subobject/Textpresso-23http%3A-2F-2Ftextpresso.org.md
git mv Special%3ASearchByProperty/Has-20subobject/Textpresso-23http:-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F.md Special%3ASearchByProperty/Has-20subobject/Textpresso-23http%3A-2F-2Ftextpresso.yeastgenome.org-2Ftextpresso-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Textpresso-23http:-2F-2Fwhis.caltech.edu-2Ftextpresso-2F.md Special%3ASearchByProperty/Has-20subobject/Textpresso-23http%3A-2F-2Fwhis.caltech.edu-2Ftextpresso-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Textpresso-23http:-2F-2Fwww.textpresso.org-2Fcelegans-2F.md Special%3ASearchByProperty/Has-20subobject/Textpresso-23http%3A-2F-2Fwww.textpresso.org-2Fcelegans-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/Tripal-23http:-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation.md Special%3ASearchByProperty/Has-20subobject/Tripal-23http%3A-2F-2Ftripal.info-2Ftutorials-2Fv2.x-2Finstallation.md
git mv Special%3ASearchByProperty/Has-20subobject/Tripal-23http:-2F-2Ftripal.info.md Special%3ASearchByProperty/Has-20subobject/Tripal-23http%3A-2F-2Ftripal.info.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo-23http:-2F-2Fcode.google.com-2Fp-2Fgenomancer.md Special%3ASearchByProperty/Has-20subobject/WebApollo-23http%3A-2F-2Fcode.google.com-2Fp-2Fgenomancer.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo-23http:-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F.md Special%3ASearchByProperty/Has-20subobject/WebApollo-23http%3A-2F-2Fgenomearchitect.org-2Fwebapollo-2Freleases-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo-23http:-2F-2Fgenomearchitect.org.md Special%3ASearchByProperty/Has-20subobject/WebApollo-23http%3A-2F-2Fgenomearchitect.org.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo-23http:-2F-2Fgenomearchitect.org:8080-2FWebApolloDemo-2F.md Special%3ASearchByProperty/Has-20subobject/WebApollo-23http%3A-2F-2Fgenomearchitect.org%3A8080-2FWebApolloDemo-2F.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo-23https:-2F-2Fgithub.com-2Fgmod-2Fapollo.md Special%3ASearchByProperty/Has-20subobject/WebApollo-23https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo2-23http:-2F-2Fgenomearchitect.org.md Special%3ASearchByProperty/Has-20subobject/WebApollo2-23http%3A-2F-2Fgenomearchitect.org.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo2-23http:-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex.md Special%3ASearchByProperty/Has-20subobject/WebApollo2-23http%3A-2F-2Ficebox.lbl.gov-2FApollo2-2Fannotator-2Findex.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo2-23https:-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases.md Special%3ASearchByProperty/Has-20subobject/WebApollo2-23https%3A-2F-2Fgithub.com-2FGMOD-2FApollo-2Freleases.md
git mv Special%3ASearchByProperty/Has-20subobject/WebApollo2-23https:-2F-2Fgithub.com-2Fgmod-2Fapollo.md Special%3ASearchByProperty/Has-20subobject/WebApollo2-23https%3A-2F-2Fgithub.com-2Fgmod-2Fapollo.md
git mv Special%3ASearchByProperty/Has-20subobject/WebGBrowse-23http:-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md Special%3ASearchByProperty/Has-20subobject/WebGBrowse-23http%3A-2F-2Fwebgbrowse.cgb.indiana.edu-2Fwebgbrowse-2Fsoftware.html.md
git mv Special%3ASearchByProperty/Has-20subobject/WebGBrowse-23http:-2F-2Fwebgbrowse.cgb.indiana.edu.md Special%3ASearchByProperty/Has-20subobject/WebGBrowse-23http%3A-2F-2Fwebgbrowse.cgb.indiana.edu.md
git mv Special%3ASearchByProperty/Has-20subobject/XORT-23http:-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md Special%3ASearchByProperty/Has-20subobject/XORT-23http%3A-2F-2Fsourceforge.net-2Fprojects-2Fgmod-2Ffiles-2FOldFiles-2F.md
git mv Special%3ASearchByProperty/Has-20title/CoryneBase:-20Corynebacterium-20Genomic-20Resources-20and-20Analysis-20Tools-20at-20Your-20Fingertips.md Special%3ASearchByProperty/Has-20title/CoryneBase%3A-20Corynebacterium-20Genomic-20Resources-20and-20Analysis-20Tools-20at-20Your-20Fingertips.md
git mv Special%3ASearchByProperty/Has-20title/CottonGen:-20a-20genomics,-20genetics-20and-20breeding-20database-20for-20cotton-20research.md Special%3ASearchByProperty/Has-20title/CottonGen%3A-20a-20genomics,-20genetics-20and-20breeding-20database-20for-20cotton-20research.md
git mv Special%3ASearchByProperty/Has-20title/DIYA:-20a-20bacterial-20annotation-20pipeline-20for-20any-20genomics-20lab..md Special%3ASearchByProperty/Has-20title/DIYA%3A-20a-20bacterial-20annotation-20pipeline-20for-20any-20genomics-20lab..md
git mv Special%3ASearchByProperty/Has-20title/Finding-20the-20missing-20honey-20bee-20genes:-20lessons-20learned-20from-20a-20genome-20upgrade.md Special%3ASearchByProperty/Has-20title/Finding-20the-20missing-20honey-20bee-20genes%3A-20lessons-20learned-20from-20a-20genome-20upgrade.md
git mv Special%3ASearchByProperty/Has-20title/GO::TermFinder-2D-2Dopen-20source-20software-20for-20accessing-20Gene-20Ontology-20information-20and-20finding-20significantly-20enriched-20Gene-20Ontology-20terms-20associated-20with-20a-20list-20of-20genes..md Special%3ASearchByProperty/Has-20title/GO%3A%3ATermFinder-2D-2Dopen-20source-20software-20for-20accessing-20Gene-20Ontology-20information-20and-20finding-20significantly-20enriched-20Gene-20Ontology-20terms-20associated-20with-20a-20list-20of-20genes..md
git mv Special%3ASearchByProperty/Has-20title/Genomes-20Unzipped:-20Public-20Personal-20Genomics.md Special%3ASearchByProperty/Has-20title/Genomes-20Unzipped%3A-20Public-20Personal-20Genomics.md
git mv Special%3ASearchByProperty/Has-20title/Pathway-20Tools-20version-2013.0:-20integrated-20software-20for-20pathway-2Fgenome-20informatics-20and-20systems-20biology..md Special%3ASearchByProperty/Has-20title/Pathway-20Tools-20version-2013.0%3A-20integrated-20software-20for-20pathway-2Fgenome-20informatics-20and-20systems-20biology..md
git mv Special%3ASearchByProperty/Has-20title/PortEco:-20a-20resource-20for-20exploring-20bacterial-20biology-20through-20high-2Dthroughput-20data-20and-20analysis-20tools.md Special%3ASearchByProperty/Has-20title/PortEco%3A-20a-20resource-20for-20exploring-20bacterial-20biology-20through-20high-2Dthroughput-20data-20and-20analysis-20tools.md
git mv Special%3ASearchByProperty/Has-20title/The-20Aspergillus-20genome-20database:-20multispecies-20curation-20and-20incorporation-20of-20RNA-2DSeq-20data-20to-20improve-20structural-20gene-20annotations.md Special%3ASearchByProperty/Has-20title/The-20Aspergillus-20genome-20database%3A-20multispecies-20curation-20and-20incorporation-20of-20RNA-2DSeq-20data-20to-20improve-20structural-20gene-20annotations.md
git mv Special%3ASearchByProperty/Has-20title/The-20Genome-20Database-20for-20Rosaceae-20\(GDR\):-20year-2010-20update.md Special%3ASearchByProperty/Has-20title/The-20Genome-20Database-20for-20Rosaceae-20\(GDR\)%3A-20year-2010-20update.md
git mv Special%3ASearchByProperty/Has-20title/The-20database-20of-20genomic-20variants:-20a-20curated-20collection-20of-20structural-20variation-20in-20the-20human-20genome.md Special%3ASearchByProperty/Has-20title/The-20database-20of-20genomic-20variants%3A-20a-20curated-20collection-20of-20structural-20variation-20in-20the-20human-20genome.md
git mv Special%3ASearchByProperty/Has-20title/The-20generic-20genome-20browser:-20a-20building-20block-20for-20a-20model-20organism-20system-20database..md Special%3ASearchByProperty/Has-20title/The-20generic-20genome-20browser%3A-20a-20building-20block-20for-20a-20model-20organism-20system-20database..md
git mv Special%3ASearchByProperty/Has-20title/Tripal:-20a-20construction-20toolkit-20for-20online-20genome-20databases..md Special%3ASearchByProperty/Has-20title/Tripal%3A-20a-20construction-20toolkit-20for-20online-20genome-20databases..md
git mv Special%3ASearchByProperty/Has-20title/WormBase-202014:-20new-20views-20of-20curated-20biology.md Special%3ASearchByProperty/Has-20title/WormBase-202014%3A-20new-20views-20of-20curated-20biology.md
git mv Special%3ASearchByProperty/Has-20title/mRNA-2DSeq-20and-20microarray-20development-20for-20the-20Grooved-20carpet-20shell-20clam,-20Ruditapes-20decussatus:-20a-20functional-20approach-20to-20unravel-20host-20-2Dparasite-20interaction.md Special%3ASearchByProperty/Has-20title/mRNA-2DSeq-20and-20microarray-20development-20for-20the-20Grooved-20carpet-20shell-20clam,-20Ruditapes-20decussatus%3A-20a-20functional-20approach-20to-20unravel-20host-20-2Dparasite-20interaction.md
git mv Special%3ASearchByProperty/Has-20topic/GO::TermFinder.md Special%3ASearchByProperty/Has-20topic/GO%3A%3ATermFinder.md
git mv Special%3ASearchByProperty/Has-20website/http:-2F-2Fbiodig.org.md Special%3ASearchByProperty/Has-20website/http%3A-2F-2Fbiodig.org.md
git mv Special%3ASearchByProperty/Has-20website/http:-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md Special%3ASearchByProperty/Has-20website/http%3A-2F-2Fbioinformatics.ai.sri.com-2Fptools-2F.md
git mv Special%3ASearchByProperty/Has-20website/http:-2F-2Fgmod.org-2Fwiki-2FXORT.md Special%3ASearchByProperty/Has-20website/http%3A-2F-2Fgmod.org-2Fwiki-2FXORT.md
git mv Special%3ASearchByProperty/Has-20website/http:-2F-2Fwebgbrowse.cgb.indiana.edu.md Special%3ASearchByProperty/Has-20website/http%3A-2F-2Fwebgbrowse.cgb.indiana.edu.md
git mv Special%3ASearchByProperty/Has-20website/http:-2F-2Fwww.sequenceontology.org-2Fwiki-2Findex.php-2FSOBA_-2D_Sequence_Ontology_Bioinformatics_Analysis.md Special%3ASearchByProperty/Has-20website/http%3A-2F-2Fwww.sequenceontology.org-2Fwiki-2Findex.php-2FSOBA_-2D_Sequence_Ontology_Bioinformatics_Analysis.md
git mv Special%3ASearchByProperty/Linktitle/Genomes-20Unzipped:-20Public-20Personal-20Genomics.md Special%3ASearchByProperty/Linktitle/Genomes-20Unzipped%3A-20Public-20Personal-20Genomics.md
git mv Special%3ASearchByProperty/Published-20in/Database-20:-20the-20journal-20of-20biological-20databases-20and-20curation.md Special%3ASearchByProperty/Published-20in/Database-20%3A-20the-20journal-20of-20biological-20databases-20and-20curation.md
git mv Special%3ASearchByProperty/Talk:Bio/Schema.md Special%3ASearchByProperty/Talk%3ABio/Schema.md
git mv Special:Categories.md Special%3ACategories.md
git mv Special:PageProperty/BioMart::Available_on_platform.md Special%3APageProperty/BioMart%3A%3AAvailable_on_platform.md
git mv Special:PageProperty/BioMart::Has_subobject.md Special%3APageProperty/BioMart%3A%3AHas_subobject.md
git mv Special:PageProperty/BioMart::Tool_functionality_or_classification.md Special%3APageProperty/BioMart%3A%3ATool_functionality_or_classification.md
git mv Special:PageProperty/CMap::Has_URL.md Special%3APageProperty/CMap%3A%3AHas_URL.md
git mv Special:PageProperty/CMap::Has_description.md Special%3APageProperty/CMap%3A%3AHas_description.md
git mv Special:PageProperty/CMap::Has_subobject.md Special%3APageProperty/CMap%3A%3AHas_subobject.md
git mv Special:PageProperty/CMap::Has_title.md Special%3APageProperty/CMap%3A%3AHas_title.md
git mv Special:PageProperty/CMap::Link_type.md Special%3APageProperty/CMap%3A%3ALink_type.md
git mv Special:PageProperty/Canto::Available_on_platform.md Special%3APageProperty/Canto%3A%3AAvailable_on_platform.md
git mv Special:PageProperty/Canto::Has_URL.md Special%3APageProperty/Canto%3A%3AHas_URL.md
git mv Special:PageProperty/Canto::Has_subobject.md Special%3APageProperty/Canto%3A%3AHas_subobject.md
git mv Special:PageProperty/Canto::Link_type.md Special%3APageProperty/Canto%3A%3ALink_type.md
git mv Special:PageProperty/GBrowse::Has_URL.md Special%3APageProperty/GBrowse%3A%3AHas_URL.md
git mv Special:PageProperty/GBrowse::Has_subobject.md Special%3APageProperty/GBrowse%3A%3AHas_subobject.md
git mv Special:PageProperty/GBrowse::Link_type.md Special%3APageProperty/GBrowse%3A%3ALink_type.md
git mv Special:PageProperty/GBrowse_syn::Has_URL.md Special%3APageProperty/GBrowse_syn%3A%3AHas_URL.md
git mv Special:PageProperty/GBrowse_syn::Has_subobject.md Special%3APageProperty/GBrowse_syn%3A%3AHas_subobject.md
git mv Special:PageProperty/GBrowse_syn::Has_title.md Special%3APageProperty/GBrowse_syn%3A%3AHas_title.md
git mv Special:PageProperty/GBrowse_syn::Link_type.md Special%3APageProperty/GBrowse_syn%3A%3ALink_type.md
git mv Special:PageProperty/GO::TermFinder::Available_on_platform.md Special%3APageProperty/GO%3A%3ATermFinder%3A%3AAvailable_on_platform.md
git mv Special:PageProperty/GO_Graphic_Viewer::Available_on_platform.md Special%3APageProperty/GO_Graphic_Viewer%3A%3AAvailable_on_platform.md
git mv Special:PageProperty/Galaxy::Has_URL.md Special%3APageProperty/Galaxy%3A%3AHas_URL.md
git mv Special:PageProperty/Galaxy::Has_input_format.md Special%3APageProperty/Galaxy%3A%3AHas_input_format.md
git mv Special:PageProperty/Galaxy::Has_subobject.md Special%3APageProperty/Galaxy%3A%3AHas_subobject.md
git mv Special:PageProperty/Galaxy::Has_title.md Special%3APageProperty/Galaxy%3A%3AHas_title.md
git mv Special:PageProperty/Galaxy::Link_type.md Special%3APageProperty/Galaxy%3A%3ALink_type.md
git mv Special:PageProperty/Galaxy::Tool_functionality_or_classification.md Special%3APageProperty/Galaxy%3A%3ATool_functionality_or_classification.md
git mv Special:PageProperty/InterMine::Has_URL.md Special%3APageProperty/InterMine%3A%3AHas_URL.md
git mv Special:PageProperty/InterMine::Has_input_format.md Special%3APageProperty/InterMine%3A%3AHas_input_format.md
git mv Special:PageProperty/InterMine::Has_output_format.md Special%3APageProperty/InterMine%3A%3AHas_output_format.md
git mv Special:PageProperty/InterMine::Has_subobject.md Special%3APageProperty/InterMine%3A%3AHas_subobject.md
git mv Special:PageProperty/InterMine::Has_title.md Special%3APageProperty/InterMine%3A%3AHas_title.md
git mv Special:PageProperty/InterMine::Interacts_with.md Special%3APageProperty/InterMine%3A%3AInteracts_with.md
git mv Special:PageProperty/InterMine::Link_type.md Special%3APageProperty/InterMine%3A%3ALink_type.md
git mv Special:PageProperty/JBrowse2::Has_URL.md Special%3APageProperty/JBrowse2%3A%3AHas_URL.md
git mv Special:PageProperty/JBrowse2::Has_input_format.md Special%3APageProperty/JBrowse2%3A%3AHas_input_format.md
git mv Special:PageProperty/JBrowse2::Has_subobject.md Special%3APageProperty/JBrowse2%3A%3AHas_subobject.md
git mv Special:PageProperty/JBrowse2::Link_type.md Special%3APageProperty/JBrowse2%3A%3ALink_type.md
git mv Special:PageProperty/JBrowse::Has_URL.md Special%3APageProperty/JBrowse%3A%3AHas_URL.md
git mv Special:PageProperty/JBrowse::Has_input_format.md Special%3APageProperty/JBrowse%3A%3AHas_input_format.md
git mv Special:PageProperty/JBrowse::Has_subobject.md Special%3APageProperty/JBrowse%3A%3AHas_subobject.md
git mv Special:PageProperty/JBrowse::Has_title.md Special%3APageProperty/JBrowse%3A%3AHas_title.md
git mv Special:PageProperty/JBrowse::Link_type.md Special%3APageProperty/JBrowse%3A%3ALink_type.md
git mv Special:PageProperty/MAKER::Has_URL.md Special%3APageProperty/MAKER%3A%3AHas_URL.md
git mv Special:PageProperty/MAKER::Has_description.md Special%3APageProperty/MAKER%3A%3AHas_description.md
git mv Special:PageProperty/MAKER::Has_subobject.md Special%3APageProperty/MAKER%3A%3AHas_subobject.md
git mv Special:PageProperty/MAKER::Has_title.md Special%3APageProperty/MAKER%3A%3AHas_title.md
git mv Special:PageProperty/MAKER::Link_type.md Special%3APageProperty/MAKER%3A%3ALink_type.md
git mv Special:PageProperty/News/GMOD_Paper_Cuts,_Dec_6th,_2013::Has_title.md Special%3APageProperty/News/GMOD_Paper_Cuts,_Dec_6th,_2013%3A%3AHas_title.md
git mv Special:PageProperty/News/GMOD_Paper_Cuts,_Feb_10th,_2014::Has_title.md Special%3APageProperty/News/GMOD_Paper_Cuts,_Feb_10th,_2014%3A%3AHas_title.md
git mv Special:PageProperty/News/GMOD_Paper_Cuts,_Nov_15th,_2013::Has_title.md Special%3APageProperty/News/GMOD_Paper_Cuts,_Nov_15th,_2013%3A%3AHas_title.md
git mv Special:PageProperty/News/GMOD_Paper_Cuts,_Nov_22nd,_2013::Has_title.md Special%3APageProperty/News/GMOD_Paper_Cuts,_Nov_22nd,_2013%3A%3AHas_title.md
git mv Special:PageProperty/News/GMOD_Paper_Cuts,_Nov_8th,_2013::Has_title.md Special%3APageProperty/News/GMOD_Paper_Cuts,_Nov_8th,_2013%3A%3AHas_title.md
git mv Special:PageProperty/Pathway_Tools::Available_on_platform.md Special%3APageProperty/Pathway_Tools%3A%3AAvailable_on_platform.md
git mv Special:PageProperty/Pathway_Tools::Has_URL.md Special%3APageProperty/Pathway_Tools%3A%3AHas_URL.md
git mv Special:PageProperty/Pathway_Tools::Has_subobject.md Special%3APageProperty/Pathway_Tools%3A%3AHas_subobject.md
git mv Special:PageProperty/Pathway_Tools::Has_title.md Special%3APageProperty/Pathway_Tools%3A%3AHas_title.md
git mv Special:PageProperty/Pathway_Tools::Link_type.md Special%3APageProperty/Pathway_Tools%3A%3ALink_type.md
git mv Special:PageProperty/Pathway_Tools::Tool_functionality_or_classification.md Special%3APageProperty/Pathway_Tools%3A%3ATool_functionality_or_classification.md
git mv Special:PageProperty/Property:Available_on_platform::Allows_value.md Special%3APageProperty/Property%3AAvailable_on_platform%3A%3AAllows_value.md
git mv Special:PageProperty/Property:Has_software_maturity_status::Allows_value.md Special%3APageProperty/Property%3AHas_software_maturity_status%3A%3AAllows_value.md
git mv Special:PageProperty/Property:Link_type::Allows_value.md Special%3APageProperty/Property%3ALink_type%3A%3AAllows_value.md
git mv Special:PageProperty/Textpresso::Has_URL.md Special%3APageProperty/Textpresso%3A%3AHas_URL.md
git mv Special:PageProperty/Textpresso::Has_subobject.md Special%3APageProperty/Textpresso%3A%3AHas_subobject.md
git mv Special:PageProperty/Textpresso::Has_title.md Special%3APageProperty/Textpresso%3A%3AHas_title.md
git mv Special:PageProperty/Textpresso::Link_type.md Special%3APageProperty/Textpresso%3A%3ALink_type.md
git mv Special:PageProperty/Tripal::Available_on_platform.md Special%3APageProperty/Tripal%3A%3AAvailable_on_platform.md
git mv Special:PageProperty/Tripal::Has_input_format.md Special%3APageProperty/Tripal%3A%3AHas_input_format.md
git mv Special:PageProperty/Tripal::Has_subobject.md Special%3APageProperty/Tripal%3A%3AHas_subobject.md
git mv Special:PageProperty/Tripal::Interacts_with.md Special%3APageProperty/Tripal%3A%3AInteracts_with.md
git mv Special:PageProperty/WebApollo2::Has_URL.md Special%3APageProperty/WebApollo2%3A%3AHas_URL.md
git mv Special:PageProperty/WebApollo2::Has_subobject.md Special%3APageProperty/WebApollo2%3A%3AHas_subobject.md
git mv Special:PageProperty/WebApollo2::Link_type.md Special%3APageProperty/WebApollo2%3A%3ALink_type.md
git mv Special:PageProperty/WebApollo::Has_URL.md Special%3APageProperty/WebApollo%3A%3AHas_URL.md
git mv Special:PageProperty/WebApollo::Has_subobject.md Special%3APageProperty/WebApollo%3A%3AHas_subobject.md
git mv Special:PageProperty/WebApollo::Has_title.md Special%3APageProperty/WebApollo%3A%3AHas_title.md
git mv Special:PageProperty/WebApollo::Link_type.md Special%3APageProperty/WebApollo%3A%3ALink_type.md
git mv Special:PageProperty/WebGBrowse::Link_type.md Special%3APageProperty/WebGBrowse%3A%3ALink_type.md
git mv Special:PopularPages.md Special%3APopularPages.md
git mv Special:RequestAccount.md Special%3ARequestAccount.md
git mv Special:Search.1.md Special%3ASearch.1.md
git mv Special:Search/!FixAfterUpgrade.md Special%3ASearch/!FixAfterUpgrade.md
git mv Special:Search/2013_Summer_School.md Special%3ASearch/2013_Summer_School.md
git mv Special:Search/Database.md Special%3ASearch/Database.md
git mv Special:Search/Deprecated.md Special%3ASearch/Deprecated.md
git mv Special:Search/File_Formats.md Special%3ASearch/File_Formats.md
git mv Special:Search/GMOD_Online_Training.md Special%3ASearch/GMOD_Online_Training.md
git mv Special:Search/GSOC.md Special%3ASearch/GSOC.md
git mv Special:Search/Generic_Gene_Pages.md Special%3ASearch/Generic_Gene_Pages.md
git mv Special:Search/Install.md Special%3ASearch/Install.md
git mv Special:Search/Jobs.md Special%3ASearch/Jobs.md
git mv Special:Search/Pages_containing_blacklisted_links.md Special%3ASearch/Pages_containing_blacklisted_links.md
git mv Special:Search/Pages_with_broken_file_links.md Special%3ASearch/Pages_with_broken_file_links.md
git mv Special:Search/Performance.md Special%3ASearch/Performance.md
git mv Special:Search/REST.md Special%3ASearch/REST.md
git mv Special:Search/RPC.md Special%3ASearch/RPC.md
git mv Special:Search/Rails.md Special%3ASearch/Rails.md
git mv Special:Search/Reactome.md Special%3ASearch/Reactome.md
git mv Special:Search/SAMtools.md Special%3ASearch/SAMtools.md
git mv Special:Search/SemanticLink.md Special%3ASearch/SemanticLink.md
git mv Special:Search/Session.md Special%3ASearch/Session.md
git mv Special:Search/Social_Media.md Special%3ASearch/Social_Media.md
git mv Special:Search/Software_Engineer.md Special%3ASearch/Software_Engineer.md
git mv Special:Search/Template.md Special%3ASearch/Template.md
git mv Special:Search/Tools_using_GMOD.md Special%3ASearch/Tools_using_GMOD.md
git mv Special:Search/Tutorial.md Special%3ASearch/Tutorial.md
git mv Special:Search/Users.md Special%3ASearch/Users.md
git mv Special:SpecialPages.md Special%3ASpecialPages.md
git mv Special:Types/Date.md Special%3ATypes/Date.md
git mv Special:Types/Page.md Special%3ATypes/Page.md
git mv Special:Types/Text.md Special%3ATypes/Text.md
git mv Special:Types/URL.md Special%3ATypes/URL.md
git mv Special:UncategorizedPages.md Special%3AUncategorizedPages.md
