git mv Property:Allows_value.md Property%3AAllows_value.md
git mv Property:Available_on_platform.md Property%3AAvailable_on_platform.md
git mv Property:Has_URL.md Property%3AHas_URL.md
git mv Property:Has_default_form.md Property%3AHas_default_form.md
git mv Property:Has_description.md Property%3AHas_description.md
git mv Property:Has_development_status.md Property%3AHas_development_status.md
git mv Property:Has_download_URL.md Property%3AHas_download_URL.md
git mv Property:Has_input_format.md Property%3AHas_input_format.md
git mv Property:Has_licence.md Property%3AHas_licence.md
git mv Property:Has_logo.md Property%3AHas_logo.md
git mv Property:Has_output_format.md Property%3AHas_output_format.md
git mv Property:Has_software_maturity_status.md Property%3AHas_software_maturity_status.md
git mv Property:Has_software_prerequisite.md Property%3AHas_software_prerequisite.md
git mv Property:Has_subobject.md Property%3AHas_subobject.md
git mv Property:Has_support_status.md Property%3AHas_support_status.md
git mv Property:Has_title.md Property%3AHas_title.md
git mv Property:Has_topic.md Property%3AHas_topic.md
git mv Property:Has_type.md Property%3AHas_type.md
git mv Property:Has_website.md Property%3AHas_website.md
git mv Property:Interaction_type.md Property%3AInteraction_type.md
git mv Property:Interacts_with.md Property%3AInteracts_with.md
git mv Property:Is_open_source.md Property%3AIs_open_source.md
git mv Property:Link_type.md Property%3ALink_type.md
git mv Property:Linktitle.md Property%3ALinktitle.md
git mv Property:Linktype.md Property%3ALinktype.md
git mv Property:Release_date.md Property%3ARelease_date.md
git mv Property:Subject.md Property%3ASubject.md
git mv Property:Tool_functionality_or_classification.md Property%3ATool_functionality_or_classification.md
git mv Property:Written_in_language.md Property%3AWritten_in_language.md
