git mv News/DIYA:_Do_It_Yourself_Annotator.md News/DIYA%3A_Do_It_Yourself_Annotator.md
git mv News/GCC2014:_June_30_-_July_2.md News/GCC2014%3A_June_30_-_July_2.md
git mv News/GMOD:_Spread_the_Word!.md News/GMOD%3A_Spread_the_Word!.md
git mv News/ISMB_2013:_Automated_Function_Prediction.md News/ISMB_2013%3A_Automated_Function_Prediction.md
git mv News/Intern_@_Aniseed:_work_on_Chado.md News/Intern_@_Aniseed%3A_work_on_Chado.md
git mv News/MAKER-P:_an_annotation_pipeline_for_plants.md News/MAKER-P%3A_an_annotation_pipeline_for_plants.md
git mv News/MaizeGDB:_Choosing_GBrowse.md News/MaizeGDB%3A_Choosing_GBrowse.md
git mv News/Pathway_Tools_2010:_Virtual,_Now.md News/Pathway_Tools_2010%3A_Virtual,_Now.md
git mv News/Server_Maintenance:_Sept_9.md News/Server_Maintenance%3A_Sept_9.md
git mv News/Tripal:_A_Web_Front_End_for_Chado.md News/Tripal%3A_A_Web_Front_End_for_Chado.md
git mv News/Website_Down:_Aug_11_2008.md News/Website_Down%3A_Aug_11_2008.md
git mv News/YAPC::NA_2010_is_Almost_Here!.md News/YAPC:%3ANA_2010_is_Almost_Here!.md
