git mv Category%3A!FixAfterUpgrade.md Category%3A!FixAfterUpgrade.md
git mv Category%3A!Lacking_ERD.md Category%3A!Lacking_ERD.md
git mv Category%3A2011_Spring_Training.md Category%3A2011_Spring_Training.md
git mv Category%3A2012_Summer_School.md Category%3A2012_Summer_School.md
git mv Category%3A2013_Summer_School.md Category%3A2013_Summer_School.md
git mv Category%3AAJAX.md Category%3AAJAX.md
git mv Category%3AAnalysis.md Category%3AAnalysis.md
git mv Category%3AAnnotation.md Category%3AAnnotation.md
git mv Category%3AApiDB.md Category%3AApiDB.md
git mv Category%3AApollo.md Category%3AApollo.md
git mv Category%3ABLAST.md Category%3ABLAST.md
git mv Category%3ABioDIG.md Category%3ABioDIG.md
git mv Category%3ABioMart.md Category%3ABioMart.md
git mv Category%3ABioPerl.md Category%3ABioPerl.md
git mv Category%3ABiology.md Category%3ABiology.md
git mv Category%3ACMap.md Category%3ACMap.md
git mv Category%3ACanto.md Category%3ACanto.md
git mv Category%3ACategories.md Category%3ACategories.md
git mv Category%3AChado.md Category%3AChado.md
git mv Category%3AChado_FlyBase.md Category%3AChado_FlyBase.md
git mv Category%3AChado_Modules.md Category%3AChado_Modules.md
git mv Category%3AChado_Presentations.md Category%3AChado_Presentations.md
git mv Category%3ACloud.md Category%3ACloud.md
git mv Category%3ACommunity_Annotation.md Category%3ACommunity_Annotation.md
git mv Category%3AComparative_Genomics.md Category%3AComparative_Genomics.md
git mv Category%3AComputing.md Category%3AComputing.md
git mv Category%3AConferences.md Category%3AConferences.md
git mv Category%3AConfiguration.md Category%3AConfiguration.md
git mv Category%3ADAS.md Category%3ADAS.md
git mv Category%3ADatabase.md Category%3ADatabase.md
git mv Category%3ADatabase_Tools.md Category%3ADatabase_Tools.md
git mv Category%3ADeprecated.md Category%3ADeprecated.md
git mv Category%3ADictyBase.md Category%3ADictyBase.md
git mv Category%3ADocumentation.md Category%3ADocumentation.md
git mv Category%3ADrupal.md Category%3ADrupal.md
git mv Category%3AERD.md Category%3AERD.md
git mv Category%3AEducation_and_Outreach.md Category%3AEducation_and_Outreach.md
git mv Category%3AErgatis.md Category%3AErgatis.md
git mv Category%3AEvents.md Category%3AEvents.md
git mv Category%3AEvolution.md Category%3AEvolution.md
git mv Category%3AExpression.md Category%3AExpression.md
git mv Category%3AExternal.md Category%3AExternal.md
git mv Category%3AFAQ.md Category%3AFAQ.md
git mv Category%3AFile_Formats.md Category%3AFile_Formats.md
git mv Category%3AFlyBase.md Category%3AFlyBase.md
git mv Category%3AGBrowse.md Category%3AGBrowse.md
git mv Category%3AGBrowse_2.md Category%3AGBrowse_2.md
git mv Category%3AGBrowse_Developer.md Category%3AGBrowse_Developer.md
git mv Category%3AGBrowse_Plugins.md Category%3AGBrowse_Plugins.md
git mv Category%3AGBrowse_syn.md Category%3AGBrowse_syn.md
git mv Category%3AGFF.md Category%3AGFF.md
git mv Category%3AGFF3.md Category%3AGFF3.md
git mv Category%3AGMODWeb.md Category%3AGMODWeb.md
git mv Category%3AGMOD_Best_Practices.md Category%3AGMOD_Best_Practices.md
git mv Category%3AGMOD_Community.md Category%3AGMOD_Community.md
git mv Category%3AGMOD_Component.md Category%3AGMOD_Component.md
git mv Category%3AGMOD_Components.md Category%3AGMOD_Components.md
git mv Category%3AGMOD_Developers.md Category%3AGMOD_Developers.md
git mv Category%3AGMOD_Evo_Hackathon.md Category%3AGMOD_Evo_Hackathon.md
git mv Category%3AGMOD_Online_Training.md Category%3AGMOD_Online_Training.md
git mv Category%3AGMOD_Project.md Category%3AGMOD_Project.md
git mv Category%3AGMOD_Project_Logos.md Category%3AGMOD_Project_Logos.md
git mv Category%3AGMOD_Project_Presentations.md Category%3AGMOD_Project_Presentations.md
git mv Category%3AGMOD_Schools.md Category%3AGMOD_Schools.md
git mv Category%3AGMOD_Tools.md Category%3AGMOD_Tools.md
git mv Category%3AGMOD_Web_Site.md Category%3AGMOD_Web_Site.md
git mv Category%3AGMOD_in_the_Cloud.md Category%3AGMOD_in_the_Cloud.md
git mv Category%3AGMOD_virtual_server.md Category%3AGMOD_virtual_server.md
git mv Category%3AGalaxy.md Category%3AGalaxy.md
git mv Category%3AGeneric_Gene_Pages.md Category%3AGeneric_Gene_Pages.md
git mv Category%3AGramene.md Category%3AGramene.md
git mv Category%3AHOWTO.md Category%3AHOWTO.md
git mv Category%3AHelp.md Category%3AHelp.md
git mv Category%3AIGS.md Category%3AIGS.md
git mv Category%3AInstall.md Category%3AInstall.md
git mv Category%3AInterMine.md Category%3AInterMine.md
git mv Category%3AJBrowse.md Category%3AJBrowse.md
git mv Category%3AJava.md Category%3AJava.md
git mv Category%3AJavascript.md Category%3AJavascript.md
git mv Category%3AJobs.md Category%3AJobs.md
git mv Category%3ALinux.md Category%3ALinux.md
git mv Category%3ALogos_and_Icons.md Category%3ALogos_and_Icons.md
git mv Category%3ALuceGene.md Category%3ALuceGene.md
git mv Category%3AMAKER.md Category%3AMAKER.md
git mv Category%3AMGI.md Category%3AMGI.md
git mv Category%3AMOD_UI_Presentations.md Category%3AMOD_UI_Presentations.md
git mv Category%3AMOD_User_Interfaces.md Category%3AMOD_User_Interfaces.md
git mv Category%3AMac_OS_X.md Category%3AMac_OS_X.md
git mv Category%3AMeetings.md Category%3AMeetings.md
git mv Category%3AMember_Logos.md Category%3AMember_Logos.md
git mv Category%3AMicroarrays.md Category%3AMicroarrays.md
git mv Category%3AMiddleware.md Category%3AMiddleware.md
git mv Category%3AMiddleware_Presentations.md Category%3AMiddleware_Presentations.md
git mv Category%3AModware.md Category%3AModware.md
git mv Category%3AMySQL.md Category%3AMySQL.md
git mv Category%3ANGS.md Category%3ANGS.md
git mv Category%3ANatural_Diversity.md Category%3ANatural_Diversity.md
git mv Category%3ANeeds_Editing.md Category%3ANeeds_Editing.md
git mv Category%3ANeeds_Testing.md Category%3ANeeds_Testing.md
git mv Category%3ANews_Items.md Category%3ANews_Items.md
git mv Category%3AOntologies.md Category%3AOntologies.md
git mv Category%3APages_containing_blacklisted_links.md Category%3APages_containing_blacklisted_links.md
git mv Category%3APages_with_broken_file_links.md Category%3APages_with_broken_file_links.md
git mv Category%3APages_with_problems_or_questions.md Category%3APages_with_problems_or_questions.md
git mv Category%3APaper_Cuts.md Category%3APaper_Cuts.md
git mv Category%3AParameciumDB.md Category%3AParameciumDB.md
git mv Category%3APathway_Tools.md Category%3APathway_Tools.md
git mv Category%3APerformance.md Category%3APerformance.md
git mv Category%3APerl.md Category%3APerl.md
git mv Category%3APhenotypes.md Category%3APhenotypes.md
git mv Category%3APosters.md Category%3APosters.md
git mv Category%3APostgreSQL.md Category%3APostgreSQL.md
git mv Category%3APresentations.md Category%3APresentations.md
git mv Category%3AProposals.md Category%3AProposals.md
git mv Category%3APubSearch.md Category%3APubSearch.md
git mv Category%3APublications.md Category%3APublications.md
git mv Category%3AREST.md Category%3AREST.md
git mv Category%3ARGD.md Category%3ARGD.md
git mv Category%3ARPC.md Category%3ARPC.md
git mv Category%3ARails.md Category%3ARails.md
git mv Category%3AReactome.md Category%3AReactome.md
git mv Category%3ASAMtools.md Category%3ASAMtools.md
git mv Category%3ASGD.md Category%3ASGD.md
git mv Category%3ASGN.md Category%3ASGN.md
git mv Category%3ASOBA.md Category%3ASOBA.md
git mv Category%3AScreenshots.md Category%3AScreenshots.md
git mv Category%3ASemanticLink.md Category%3ASemanticLink.md
git mv Category%3ASemantic_web.md Category%3ASemantic_web.md
git mv Category%3ASession.md Category%3ASession.md
git mv Category%3ASocial_Media.md Category%3ASocial_Media.md
git mv Category%3ASoftware_Engineer.md Category%3ASoftware_Engineer.md
git mv Category%3ASybil.md Category%3ASybil.md
git mv Category%3ATAIR.md Category%3ATAIR.md
git mv Category%3ATableEdit.md Category%3ATableEdit.md
git mv Category%3ATemplate.md Category%3ATemplate.md
git mv Category%3ATextpresso.md Category%3ATextpresso.md
git mv Category%3ATool_data.md Category%3ATool_data.md
git mv Category%3ATools_using_GMOD.md Category%3ATools_using_GMOD.md
git mv Category%3ATripal.md Category%3ATripal.md
git mv Category%3ATurnkey.md Category%3ATurnkey.md
git mv Category%3ATutorial.md Category%3ATutorial.md
git mv Category%3ATutorials.md Category%3ATutorials.md
git mv Category%3AUnder_Construction.md Category%3AUnder_Construction.md
git mv Category%3AUnsupported.md Category%3AUnsupported.md
git mv Category%3AUser_Experiences.md Category%3AUser_Experiences.md
git mv Category%3AUsers.md Category%3AUsers.md
git mv Category%3AVisualization.md Category%3AVisualization.md
git mv Category%3AWFleaBase.md Category%3AWFleaBase.md
git mv Category%3AWebGBrowse.md Category%3AWebGBrowse.md
git mv Category%3AWeb_services.md Category%3AWeb_services.md
git mv Category%3AWebapollo-minutes.md Category%3AWebapollo-minutes.md
git mv Category%3AWiki_Tools.md Category%3AWiki_Tools.md
git mv Category%3AWindows.md Category%3AWindows.md
git mv Category%3AWormBase.md Category%3AWormBase.md
git mv Category%3AXML.md Category%3AXML.md
git mv Category%3AXORT.md Category%3AXORT.md
